class <C <U <root>>> < <C <U Object>> ()
  class <S <C <U <root>>> $1>[<C <U <AttachedClass>>>] < <S <C <U Object>> $1> ()
    method <S <C <U <root>>> $1>#<N <U <static-init>> $CENSORED> (<blk>) @ Loc {file=test/testdata/desugar/destructure.rb start=3:1 end=10:4}
      argument <blk><block> @ Loc {file=test/testdata/desugar/destructure.rb start=??? end=???}
  class <C <U Destructure>> < <C <U Object>> () @ Loc {file=test/testdata/desugar/destructure.rb start=3:1 end=3:18}
    method <C <U Destructure>>#<U f> ((x,y), z, <blk>) @ Loc {file=test/testdata/desugar/destructure.rb start=4:3 end=4:18}
      argument (x,y)<> @ Loc {file=test/testdata/desugar/destructure.rb start=4:9 end=4:14}
      argument z<> @ Loc {file=test/testdata/desugar/destructure.rb start=4:16 end=4:17}
      argument <blk><block> @ Loc {file=test/testdata/desugar/destructure.rb start=??? end=???}
  class <S <C <U Destructure>> $1>[<C <U <AttachedClass>>>] < <S <C <U Object>> $1> () @ Loc {file=test/testdata/desugar/destructure.rb start=3:1 end=3:18}
    type-member(+) <S <C <U Destructure>> $1>::<C <U <AttachedClass>>> -> LambdaParam(<S <C <U Destructure>> $1>::<C <U <AttachedClass>>>, lower=T.noreturn, upper=Destructure) @ Loc {file=test/testdata/desugar/destructure.rb start=3:1 end=3:18}
    method <S <C <U Destructure>> $1>#<U <static-init>> (<blk>) @ Loc {file=test/testdata/desugar/destructure.rb start=3:1 end=10:4}
      argument <blk><block> @ Loc {file=test/testdata/desugar/destructure.rb start=??? end=???}

