class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    <self>.extend(<emptyTree>::<C T>::<C Sig>)

    <self>.sig() do ||
      <self>.params(:x, <emptyTree>::<C Integer>, :y, <emptyTree>::<C T>.nilable(<emptyTree>::<C String>)).void()
    end

    def initialize<<todo method>>(x, y = nil, &<blk>)
      begin
        @x = x
        @y = y
      end
    end
  end
end
