class <emptyTree><<C <root>>> < (::<todo sym>)
end
class <emptyTree><<C <root>>> < (::<todo sym>)
  <emptyTree>::<C A> = <emptyTree>::<C DoesNotExist>
end
class <emptyTree><<C <root>>> < (::<todo sym>)
  <self>.extend(<emptyTree>::<C T>::<C Sig>)

  <self>.sig() do ||
    <self>.params(:x, <emptyTree>::<C A>).void()
  end

  def example<<todo method>>(x, &<blk>)
    <emptyTree>::<C T>.reveal_type(x)
  end
end
