# -- test/testdata/rbs/signatures_defs_abstract_autocorrect.rb --
# typed: strict
# enable-experimental-rbs-comments: true

# @abstract
class Abstract
  # @abstract
  #: -> void
  def foo = super # error: Methods declared @abstract with an RBS comment must always call super

  # @abstract
  #: -> void
  def bar
    super # error: Methods declared @abstract with an RBS comment must always call super
  end

  # @abstract
  #: -> void
  def baz # error: Methods declared @abstract with an RBS comment must always call super
    super # error: Abstract methods must not contain any code in their body
  end

  # @abstract
  #: -> void
  def qux # error: Methods declared @abstract with an RBS comment must always call super
    super
  end

  # @abstract
  #: -> void
  def self.foo = super # error: Methods declared @abstract with an RBS comment must always call super

  # @abstract
  #: -> void
  def self.bar
    super # error: Methods declared @abstract with an RBS comment must always call super
  end

  # @abstract
  #: -> void
  def self.baz # error: Methods declared @abstract with an RBS comment must always call super
    super # error: Abstract methods must not contain any code in their body
  end

  # @abstract
  #: -> void
  def self.qux # error: Methods declared @abstract with an RBS comment must always call super
    super
  end
end
# ------------------------------
