Class {
  name = Const {
    scope = NULL
    name = <C <U A>>
  }
  superclass = NULL
  body = Begin {
    stmts = [
      Class {
        name = Const {
          scope = NULL
          name = <C <U Inner>>
        }
        superclass = NULL
        body = NULL
      }
      DefMethod {
        name = <U method1>
        args = NULL
        body = NULL
      }
      DefMethod {
        name = <U method2>
        args = NULL
        body = NULL
      }
    ]
  }
}
