ClassDef{
  kind = class
  name = EmptyTree
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    Send{
      flags = {privateOk}
      recv = Self
      fun = <U foo>
      block = Block {
        params = [
          UnresolvedIdent{
            kind = Local
            name = <D <U <destructure>> $9>
          }
        ]
        body = InsSeq{
          stats = [
            InsSeq{
              stats = [
                Assign{
                  lhs = UnresolvedIdent{
                    kind = Local
                    name = <D <U <assignTemp>> $10>
                  }
                  rhs = UnresolvedIdent{
                    kind = Local
                    name = <D <U <destructure>> $9>
                  }
                }
                Assign{
                  lhs = UnresolvedIdent{
                    kind = Local
                    name = <D <U <assignTemp>> $11>
                  }
                  rhs = Send{
                    flags = {}
                    recv = ConstantLit{
                      symbol = (class ::<Magic>)
                      orig = nullptr
                    }
                    fun = <U <expand-splat>>
                    block = nullptr
                    pos_args = 3
                    args = [
                      UnresolvedIdent{
                        kind = Local
                        name = <D <U <assignTemp>> $10>
                      }
                      Literal{ value = 1 }
                      Literal{ value = 0 }
                    ]
                  }
                }
                Assign{
                  lhs = UnresolvedIdent{
                    kind = Local
                    name = <U args>
                  }
                  rhs = Send{
                    flags = {}
                    recv = UnresolvedIdent{
                      kind = Local
                      name = <D <U <assignTemp>> $11>
                    }
                    fun = <U []>
                    block = nullptr
                    pos_args = 1
                    args = [
                      Literal{ value = 0 }
                    ]
                  }
                }
              ],
              expr = UnresolvedIdent{
                kind = Local
                name = <D <U <assignTemp>> $10>
              }
            }
          ],
          expr = Literal{ value = "block with multi-target rest args" }
        }
      }
      pos_args = 0
      args = [
      ]
    }
  ]
}
