Begin {
  stmts = [
    Class {
      name = Const {
        scope = NULL
        name = <C <U <ConstantNameMissing>>>
      }
      superclass = NULL
      body = NULL
    }
    Class {
      name = Const {
        scope = NULL
        name = <C <U <ConstantNameMissing>>>
      }
      superclass = NULL
      body = NULL
    }
    Class {
      name = Const {
        scope = NULL
        name = <C <U <ConstantNameMissing>>>
      }
      superclass = NULL
      body = DefMethod {
        name = <U bar>
        params = NULL
        body = NULL
      }
    }
  ]
}
