Begin {
  stmts = [
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Kernel>>
        }
        method = <U lambda>
        args = [
        ]
      }
      args = NULL
      body = Integer {
        val = "123"
      }
    }
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Kernel>>
        }
        method = <U lambda>
        args = [
        ]
      }
      args = Args {
        args = [
          Arg {
            name = <U foo>
          }
        ]
      }
      body = LVar {
        name = <U foo>
      }
    }
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Kernel>>
        }
        method = <U lambda>
        args = [
        ]
      }
      args = Args {
        args = [
          Optarg {
            name = <U foo>
            default_ = Integer {
              val = "123"
            }
          }
        ]
      }
      body = LVar {
        name = <U foo>
      }
    }
    Send {
      receiver = Block {
        send = Send {
          receiver = Const {
            scope = NULL
            name = <C <U Kernel>>
          }
          method = <U lambda>
          args = [
          ]
        }
        args = NULL
        body = Integer {
          val = "123"
        }
      }
      method = <U call>
      args = [
      ]
    }
    Block {
      send = Send {
        receiver = NULL
        method = <U lambda>
        args = [
        ]
      }
      args = NULL
      body = Integer {
        val = "123"
      }
    }
    Block {
      send = Send {
        receiver = NULL
        method = <U lambda>
        args = [
        ]
      }
      args = Args {
        args = [
          Arg {
            name = <U foo>
          }
        ]
      }
      body = LVar {
        name = <U foo>
      }
    }
    Send {
      receiver = NULL
      method = <U foo>
      args = [
        Symbol {
          val = <U arg1>
        }
        Block {
          send = Send {
            receiver = Const {
              scope = NULL
              name = <C <U Kernel>>
            }
            method = <U lambda>
            args = [
            ]
          }
          args = NULL
          body = Integer {
            val = "123"
          }
        }
      ]
    }
    Class {
      name = Const {
        scope = NULL
        name = <C <U C>>
      }
      superclass = NULL
      body = DefMethod {
        name = <U foo>
        args = NULL
        body = Block {
          send = Send {
            receiver = Const {
              scope = NULL
              name = <C <U Kernel>>
            }
            method = <U lambda>
            args = [
            ]
          }
          args = NULL
          body = Integer {
            val = "123"
          }
        }
      }
    }
  ]
}
