Begin {
  stmts = [
    Masgn {
      lhs = Mlhs {
        exprs = [
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x>
              }
              LVarLhs {
                name = <U y>
              }
            ]
          }
          LVarLhs {
            name = <U a>
          }
        ]
      }
      rhs = Array {
        elts = [
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          LVarLhs {
            name = <U a>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x>
              }
              LVarLhs {
                name = <U y>
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          SplatLhs {
            var = LVarLhs {
              name = <U head>
            }
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x>
              }
              LVarLhs {
                name = <U y>
              }
            ]
          }
          LVarLhs {
            name = <U a>
          }
        ]
      }
      rhs = Array {
        elts = [
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          SplatLhs {
            var = LVarLhs {
              name = <U head>
            }
          }
          LVarLhs {
            name = <U a>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x>
              }
              LVarLhs {
                name = <U y>
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
        ]
      }
    }
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Proc>>
        }
        method = <U new>
        args = [
        ]
      }
      params = Params {
        params = [
          Param {
            name = <U p1>
          }
          Mlhs {
            exprs = [
              Param {
                name = <U x2>
              }
              Param {
                name = <U y2>
              }
            ]
          }
        ]
      }
      body = NULL
    }
    For {
      vars = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p1>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x2>
              }
              LVarLhs {
                name = <U y2>
              }
            ]
          }
        ]
      }
      expr = LVar {
        name = <U a>
      }
      body = NULL
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p2>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U head>
              }
              SplatLhs {
                var = NULL
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
          Array {
            elts = [
              Integer {
                val = "1"
              }
              Integer {
                val = "2"
              }
            ]
          }
          Array {
            elts = [
              Integer {
                val = "3"
              }
              Integer {
                val = "4"
              }
            ]
          }
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p3>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U head>
              }
              SplatLhs {
                var = LVarLhs {
                  name = <U tail>
                }
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
          Array {
            elts = [
              Integer {
                val = "1"
              }
              Integer {
                val = "2"
              }
            ]
          }
          Array {
            elts = [
              Integer {
                val = "3"
              }
              Integer {
                val = "4"
              }
            ]
          }
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p4>
          }
          Mlhs {
            exprs = [
              SplatLhs {
                var = NULL
              }
              LVarLhs {
                name = <U last>
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
          Array {
            elts = [
              Integer {
                val = "1"
              }
              Integer {
                val = "2"
              }
            ]
          }
          Array {
            elts = [
              Integer {
                val = "3"
              }
              Integer {
                val = "4"
              }
            ]
          }
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p5>
          }
          Mlhs {
            exprs = [
              SplatLhs {
                var = LVarLhs {
                  name = <U init>
                }
              }
              LVarLhs {
                name = <U last>
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
          Array {
            elts = [
              Integer {
                val = "1"
              }
              Integer {
                val = "2"
              }
            ]
          }
          Array {
            elts = [
              Integer {
                val = "3"
              }
              Integer {
                val = "4"
              }
            ]
          }
        ]
      }
    }
    Masgn {
      lhs = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p6>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x2>
              }
            ]
          }
        ]
      }
      rhs = Array {
        elts = [
          Array {
            elts = [
              Integer {
                val = "1"
              }
              Integer {
                val = "2"
              }
            ]
          }
          Array {
            elts = [
              Integer {
                val = "3"
              }
              Integer {
                val = "4"
              }
            ]
          }
        ]
      }
    }
    For {
      vars = Mlhs {
        exprs = [
          LVarLhs {
            name = <U p7>
          }
          Mlhs {
            exprs = [
              LVarLhs {
                name = <U x2>
              }
            ]
          }
        ]
      }
      expr = LVar {
        name = <U a>
      }
      body = NULL
    }
    DefMethod {
      name = <U method_empty>
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = NULL
    }
    DefMethod {
      name = <U method_single>
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Send {
        receiver = NULL
        method = <U statement1>
        args = [
        ]
      }
    }
    DefMethod {
      name = <U method_multi>
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Begin {
        stmts = [
          Send {
            receiver = NULL
            method = <U statement1>
            args = [
            ]
          }
          Send {
            receiver = NULL
            method = <U statement2>
            args = [
            ]
          }
        ]
      }
    }
    DefS {
      singleton = Self {
      }
      name = <U method_empty>
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = NULL
    }
    DefS {
      singleton = Self {
      }
      name = <U method_single>
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Send {
        receiver = NULL
        method = <U statement1>
        args = [
        ]
      }
    }
    DefS {
      singleton = Self {
      }
      name = <U method_multi>
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Begin {
        stmts = [
          Send {
            receiver = NULL
            method = <U statement1>
            args = [
            ]
          }
          Send {
            receiver = NULL
            method = <U statement2>
            args = [
            ]
          }
        ]
      }
    }
    Block {
      send = Send {
        receiver = NULL
        method = <U block_empty>
        args = [
        ]
      }
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = NULL
    }
    Block {
      send = Send {
        receiver = NULL
        method = <U block_single>
        args = [
        ]
      }
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Send {
        receiver = NULL
        method = <U statement1>
        args = [
        ]
      }
    }
    Block {
      send = Send {
        receiver = NULL
        method = <U block_multi>
        args = [
        ]
      }
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Begin {
        stmts = [
          Send {
            receiver = NULL
            method = <U statement1>
            args = [
            ]
          }
          Send {
            receiver = NULL
            method = <U statement2>
            args = [
            ]
          }
        ]
      }
    }
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Kernel>>
        }
        method = <U lambda>
        args = [
        ]
      }
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = NULL
    }
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Kernel>>
        }
        method = <U lambda>
        args = [
        ]
      }
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Send {
        receiver = NULL
        method = <U statement1>
        args = [
        ]
      }
    }
    Block {
      send = Send {
        receiver = Const {
          scope = NULL
          name = <C <U Kernel>>
        }
        method = <U lambda>
        args = [
        ]
      }
      params = Params {
        params = [
          Mlhs {
            exprs = [
              Param {
                name = <U x>
              }
              Param {
                name = <U y>
              }
            ]
          }
        ]
      }
      body = Begin {
        stmts = [
          Send {
            receiver = NULL
            method = <U statement1>
            args = [
            ]
          }
          Send {
            receiver = NULL
            method = <U statement2>
            args = [
            ]
          }
        ]
      }
    }
  ]
}
