class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    def test1<<todo method>>(&<blk>)
      begin
        <self>.puts("inside")
      rescue => <rescueTemp>$2
        <self>.puts("after")
        def test2<<todo method>>(&<blk>)
          begin
            <self>.puts("inside")
          rescue => <rescueTemp>$2
            <self>.puts("after")
            def test3<<todo method>>(&<blk>)
              begin
                <self>.puts("inside")
              rescue => <rescueTemp>$2
                <self>.puts("after")
                def test4<<todo method>>(&<blk>)
                  <self>.puts("inside")
                rescue => <rescueTemp>$2
                  <self>.puts("after")
                end
                ::<ErrorNode>
              end
            end
          end
        end
      end
    end
  end
end
