class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    def test1<<todo method>>(&<blk>)
      begin
        <self>.puts("before")
        <emptyTree>
        def test2<<todo method>>(&<blk>)
          begin
            <self>.puts("before")
            begin
              <assignTemp>$2 = <self>.x()
              <emptyTree>
            end
            <self>.puts("after")
          end
        end
        def test3<<todo method>>(&<blk>)
          begin
            <self>.puts("before")
            begin
              <assignTemp>$2 = <self>.x()
              if <self>.puts().===(<assignTemp>$2)
                "after"
              else
                <emptyTree>
              end
            end
            def test4<<todo method>>(&<blk>)
              begin
                <self>.puts("before")
                begin
                  <assignTemp>$2 = <self>.x()
                  if <emptyTree>::<C A>.===(<assignTemp>$2)
                    <self>.puts("after")
                  else
                    <emptyTree>
                  end
                end
                def test5<<todo method>>(&<blk>)
                  begin
                    <self>.puts("before")
                    begin
                      <assignTemp>$2 = <self>.x()
                      if <emptyTree>::<C A>.===(<assignTemp>$2)
                        <self>.puts("after")
                      else
                        <emptyTree>
                      end
                    end
                    def test6<<todo method>>(&<blk>)
                      begin
                        <self>.puts("before")
                        begin
                          <assignTemp>$2 = <self>.x()
                          if ::<ErrorNode>.===(<assignTemp>$2)
                            <self>.puts("after")
                          else
                            <emptyTree>
                          end
                        end
                        def test7<<todo method>>(&<blk>)
                          begin
                            <self>.puts("before")
                            begin
                              <assignTemp>$2 = <self>.x()
                              if <emptyTree>::<C A>.===(<assignTemp>$2)
                                <emptyTree>
                              else
                                <self>.puts("after")
                              end
                            end
                            def test8<<todo method>>(&<blk>)
                              begin
                                <self>.puts("before")
                                if <emptyTree>::<C A>
                                  <emptyTree>
                                else
                                  <self>.puts("after")
                                end
                                def test9<<todo method>>(&<blk>)
                                  begin
                                    <self>.puts("before")
                                    begin
                                      <assignTemp>$2 = <self>.x()
                                      if ::T.unsafe(::Kernel).raise("Sorbet rewriter pass partially unimplemented")
                                        <emptyTree>
                                      else
                                        <self>.puts("after")
                                      end
                                    end
                                  end
                                end
                                ::<ErrorNode>
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
