class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    class <emptyTree>::<C Inner><<C <todo sym>>> < (<emptyTree>::<C Object>)
      def method2<<todo method>>(&<blk>)
        <emptyTree>
      end
    end

    class <emptyTree>::<C B><<C <todo sym>>> < (::<todo sym>)
      class <emptyTree>::<C Inner><<C <todo sym>>> < (<emptyTree>::<C Object>)
        def method2<<todo method>>(&<blk>)
          <emptyTree>
        end
      end

      class <emptyTree>::<C C><<C <todo sym>>> < (::<todo sym>)
        class <emptyTree>::<C Inner><<C <todo sym>>> < (<emptyTree>::<C Object>)
          <self>.puts("hello")

          def method2<<todo method>>(&<blk>)
            <emptyTree>
          end
        end

        class <emptyTree>::<C D><<C <todo sym>>> < (::<todo sym>)
          class <emptyTree>::<C Inner><<C <todo sym>>> < (::<todo sym>)
            def method2<<todo method>>(&<blk>)
              <emptyTree>
            end
          end

          class <emptyTree>::<C E><<C <todo sym>>> < (::<todo sym>)
            class <emptyTree>::<C Inner><<C <todo sym>>> < (::<todo sym>)
              <self>.puts("hello")

              def method2<<todo method>>(&<blk>)
                <emptyTree>
              end
            end

            class <emptyTree>::<C F><<C <todo sym>>> < (::<todo sym>)
              class <emptyTree>::<C Inner><<C <todo sym>>> < (<emptyTree>::<C Object>)
                <self>.puts("hello")

                def method2<<todo method>>(&<blk>)
                  <emptyTree>
                end
              end

              ::<ErrorNode>
            end
          end
        end
      end
    end
  end
end
