class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    def test1<<todo method>>(&<blk>)
      begin
        if <self>.x().f()
          <emptyTree>
        else
          <emptyTree>
        end
        def test2<<todo method>>(&<blk>)
          if <self>.x().f()
            <emptyTree>
          else
            <emptyTree>
          end
        end
      end
    end

    ::<ErrorNode>
  end
end
