class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    module <emptyTree>::<C B><<C <todo sym>>> < ()
      def self.foo<<todo method>>(&<blk>)
        def bar<<todo method>>(&<blk>)
          begin
            <self>.puts("inside foo")
            <self>.puts("inside A")
            ::<ErrorNode>
          end
        end
      end
    end
  end
end
