class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    <self>.extend(<emptyTree>::<C T>::<C Sig>)

    <self>.sig() do ||
      <self>.params(:x, <emptyTree>::<C Integer>).void()
    end

    def foo<<todo method>>(x, &<blk>)
      begin
        <self>.puts(x)
        <self>.sig() do ||
          <self>.void()
        end
        def bar<<todo method>>(&<blk>)
          begin
            <self>.puts("after")
            ::<ErrorNode>
          end
        end
      end
    end
  end
end
