class <emptyTree><<C <root>>> < (::<todo sym>)
  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    def test1<<todo method>>(&<blk>)
      begin
        if <self>.x().f()
          <self>.puts("inside if")
        else
          <emptyTree>
        end
        <self>.puts("after if but inside test1")
      end
    end

    def test2<<todo method>>(&<blk>)
      if <self>.x().f()
        <emptyTree>
      else
        <emptyTree>
      end
    end

    ::<ErrorNode>
  end
end
