class <emptyTree><<C <root>>> < (::<todo sym>)
  module <emptyTree>::<C Opus>::<C Log><<C <todo sym>>> < ()
    def self.info<<todo method>>(&<blk>)
      <emptyTree>
    end
  end

  class <emptyTree>::<C A><<C <todo sym>>> < (::<todo sym>)
    def g<<todo method>>(&<blk>)
      begin
        t = <emptyTree>::<C T>.let(true, <emptyTree>::<C T>::<C Boolean>)
        f = <emptyTree>::<C T>.let(false, <emptyTree>::<C T>::<C Boolean>)
        <self>.puts(::<Magic>.<build-range>(0, 0, false))
        <self>.puts(::<Magic>.<build-range>(0, <emptyTree>, false))
        if <emptyTree>
          <emptyTree>
        else
          <emptyTree>
        end
        if <emptyTree>
          "hello"
        else
          <emptyTree>
        end
        <self>.puts(::<Magic>.<build-range>(1, 1, true))
        <self>.puts(::<Magic>.<build-range>(1, <emptyTree>, true))
        if <emptyTree>
          <emptyTree>
        else
          <emptyTree>
        end
        if <emptyTree>
          "hello"
        else
          <emptyTree>
        end
        <self>.puts(2.+(2))
        <self>.puts(2.+(::<ErrorNode>))
        if 2.+(::<ErrorNode>)
          <emptyTree>
        else
          <emptyTree>
        end
      end
    end
  end
end
