ClassDef{
  loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:1-5:4
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/block-implicit-rest-arg.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:1-5:4
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    Send{
      loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:1-5:4
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:1-3:1
        localVariable = <U <self>>
      }
      fun = <U call>
      block = Block {
        loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:1-5:4
        args = [
          UnresolvedIdent{
            loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:10-3:11
            kind = Local
            name = <U m>
          }
          UnresolvedIdent{
            loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:13-3:14
            kind = Local
            name = <U a>
          }
          RestArg{ loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:15-3:15, expr = UnresolvedIdent{
            loc = test/testdata/desugar/block-implicit-rest-arg.rb:3:15-3:15
            kind = Local
            name = <U <restargs>>
          } }
        ]
        body = Send{
          loc = test/testdata/desugar/block-implicit-rest-arg.rb:4:3-4:8
          flags = {privateOk}
          recv = Local{
            loc = test/testdata/desugar/block-implicit-rest-arg.rb:4:3-4:3
            localVariable = <U <self>>
          }
          fun = <U stuff>
          block = nullptr
          pos_args = 0
          args = [
          ]
        }
      }
      pos_args = 0
      args = [
      ]
    }
  ]
}
