ClassDef{
  loc = test/testdata/desugar/for.rb:3:1-63:10
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/for.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/for.rb:3:1-63:10
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    ClassDef{
      loc = test/testdata/desugar/for.rb:3:1-9:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/for.rb:3:7-3:8
        cnst = <C <U A>>
        scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [ConstantLit{
          loc = test/testdata/desugar/for.rb:3:1-9:4
          symbol = (class ::<todo sym>)
          orig = nullptr
        }]
      rhs = [
        MethodDef{
          loc = test/testdata/desugar/for.rb:4:5-8:8
          flags = {self}
          name = <U each><<U <todo method>>>
          args = [BlockArg{ loc = test/testdata/desugar/for.rb:4:20-4:23, expr = UnresolvedIdent{
              loc = test/testdata/desugar/for.rb:4:20-4:23
              kind = Local
              name = <U blk>
            } }]
          rhs = InsSeq{
            loc = test/testdata/desugar/for.rb:6:9-7:24
            stats = [
              Send{
                loc = test/testdata/desugar/for.rb:6:9-6:24
                flags = {}
                recv = UnresolvedIdent{
                  loc = test/testdata/desugar/for.rb:6:9-6:24
                  kind = Local
                  name = <U blk>
                }
                fun = <U call>
                block = nullptr
                pos_args = 5
                args = [
                  Literal{ loc = test/testdata/desugar/for.rb:6:15-6:16, value = 1 }
                  Literal{ loc = test/testdata/desugar/for.rb:6:17-6:18, value = 2 }
                  Literal{ loc = test/testdata/desugar/for.rb:6:19-6:20, value = 3 }
                  Literal{ loc = test/testdata/desugar/for.rb:6:21-6:22, value = 4 }
                  Literal{ loc = test/testdata/desugar/for.rb:6:23-6:24, value = 5 }
                ]
              }
            ],
            expr = Send{
              loc = test/testdata/desugar/for.rb:7:9-7:24
              flags = {}
              recv = UnresolvedIdent{
                loc = test/testdata/desugar/for.rb:7:9-7:24
                kind = Local
                name = <U blk>
              }
              fun = <U call>
              block = nullptr
              pos_args = 5
              args = [
                Literal{ loc = test/testdata/desugar/for.rb:7:15-7:16, value = 6 }
                Literal{ loc = test/testdata/desugar/for.rb:7:17-7:18, value = 7 }
                Literal{ loc = test/testdata/desugar/for.rb:7:19-7:20, value = 8 }
                Literal{ loc = test/testdata/desugar/for.rb:7:21-7:22, value = 9 }
                Literal{ loc = test/testdata/desugar/for.rb:7:23-7:24, value = 0 }
              ]
            }
          }
        }
      ]
    }

    ClassDef{
      loc = test/testdata/desugar/for.rb:11:1-18:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/for.rb:11:7-11:8
        cnst = <C <U E>>
        scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [ConstantLit{
          loc = test/testdata/desugar/for.rb:11:1-18:4
          symbol = (class ::<todo sym>)
          orig = nullptr
        }]
      rhs = [
        MethodDef{
          loc = test/testdata/desugar/for.rb:12:5-14:8
          flags = {self}
          name = <U e=><<U <todo method>>>
          args = [UnresolvedIdent{
              loc = test/testdata/desugar/for.rb:12:17-12:18
              kind = Local
              name = <U e>
            }, BlockArg{ loc = test/testdata/desugar/for.rb, expr = UnresolvedIdent{
              loc = test/testdata/desugar/for.rb
              kind = Local
              name = <U <blk>>
            } }]
          rhs = Assign{
            loc = test/testdata/desugar/for.rb:13:9-13:15
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/for.rb:13:9-13:11
              kind = Instance
              name = <U @e>
            }
            rhs = UnresolvedIdent{
              loc = test/testdata/desugar/for.rb:13:14-13:15
              kind = Local
              name = <U e>
            }
          }
        }

        MethodDef{
          loc = test/testdata/desugar/for.rb:15:5-17:8
          flags = {self}
          name = <U e><<U <todo method>>>
          args = [BlockArg{ loc = test/testdata/desugar/for.rb, expr = UnresolvedIdent{
              loc = test/testdata/desugar/for.rb
              kind = Local
              name = <U <blk>>
            } }]
          rhs = UnresolvedIdent{
            loc = test/testdata/desugar/for.rb:16:9-16:11
            kind = Instance
            name = <U @e>
          }
        }
      ]
    }

    ClassDef{
      loc = test/testdata/desugar/for.rb:20:1-62:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/for.rb:20:7-20:11
        cnst = <C <U Main>>
        scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [ConstantLit{
          loc = test/testdata/desugar/for.rb:20:1-62:4
          symbol = (class ::<todo sym>)
          orig = nullptr
        }]
      rhs = [
        MethodDef{
          loc = test/testdata/desugar/for.rb:21:5-61:8
          flags = {self}
          name = <U main><<U <todo method>>>
          args = [BlockArg{ loc = test/testdata/desugar/for.rb, expr = UnresolvedIdent{
              loc = test/testdata/desugar/for.rb
              kind = Local
              name = <U <blk>>
            } }]
          rhs = InsSeq{
            loc = test/testdata/desugar/for.rb:23:9-60:12
            stats = [
              Send{
                loc = test/testdata/desugar/for.rb:23:9-25:12
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/for.rb:23:18-23:19
                  cnst = <C <U A>>
                  scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                }
                fun = <U each>
                block = Block {
                  loc = test/testdata/desugar/for.rb:23:9-25:12
                  args = [
                    UnresolvedIdent{
                      loc = test/testdata/desugar/for.rb:23:13-23:14
                      kind = Local
                      name = <U a>
                    }
                  ]
                  body = Send{
                    loc = test/testdata/desugar/for.rb:24:13-24:27
                    flags = {privateOk}
                    recv = Local{
                      loc = test/testdata/desugar/for.rb:24:13-24:13
                      localVariable = <U <self>>
                    }
                    fun = <U puts>
                    block = nullptr
                    pos_args = 1
                    args = [
                      Send{
                        loc = test/testdata/desugar/for.rb:24:18-24:27
                        flags = {}
                        recv = UnresolvedIdent{
                          loc = test/testdata/desugar/for.rb:24:18-24:19
                          kind = Local
                          name = <U a>
                        }
                        fun = <U inspect>
                        block = nullptr
                        pos_args = 0
                        args = [
                        ]
                      }
                    ]
                  }
                }
                pos_args = 0
                args = [
                ]
              }
              Send{
                loc = test/testdata/desugar/for.rb:26:9-29:12
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/for.rb:26:9-26:10
                  cnst = <C <U A>>
                  scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                }
                fun = <U each>
                block = Block {
                  loc = test/testdata/desugar/for.rb:26:9-29:12
                  args = [
                    RestArg{ loc = test/testdata/desugar/for.rb:26:20-26:28, expr = UnresolvedIdent{
                      loc = test/testdata/desugar/for.rb:26:21-26:28
                      kind = Local
                      name = <U forTemp>
                    } }
                  ]
                  body = InsSeq{
                    loc = test/testdata/desugar/for.rb:27:13-28:27
                    stats = [
                      InsSeq{
                        loc = test/testdata/desugar/for.rb:27:13-27:26
                        stats = [
                          Assign{
                            loc = test/testdata/desugar/for.rb:27:13-27:26
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:27:13-27:26
                              kind = Local
                              name = <D <U <assignTemp>> $2>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:27:18-27:26
                              flags = {}
                              recv = ConstantLit{
                                loc = test/testdata/desugar/for.rb:27:18-27:26
                                symbol = (class ::<Magic>)
                                orig = nullptr
                              }
                              fun = <U <splat>>
                              block = nullptr
                              pos_args = 1
                              args = [
                                UnresolvedIdent{
                                  loc = test/testdata/desugar/for.rb:27:19-27:26
                                  kind = Local
                                  name = <U forTemp>
                                }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:27:13-27:26
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:27:13-27:26
                              kind = Local
                              name = <D <U <assignTemp>> $3>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:27:13-27:26
                              flags = {}
                              recv = ConstantLit{
                                loc = test/testdata/desugar/for.rb:27:13-27:26
                                symbol = (class ::<Magic>)
                                orig = nullptr
                              }
                              fun = <U <expand-splat>>
                              block = nullptr
                              pos_args = 3
                              args = [
                                UnresolvedIdent{
                                  loc = test/testdata/desugar/for.rb:27:13-27:26
                                  kind = Local
                                  name = <D <U <assignTemp>> $2>
                                }
                                Literal{ loc = test/testdata/desugar/for.rb:27:13-27:26, value = 1 }
                                Literal{ loc = test/testdata/desugar/for.rb:27:13-27:26, value = 0 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:27:13-27:14
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:27:13-27:14
                              kind = Local
                              name = <U a>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:27:13-27:14
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:27:13-27:14
                                kind = Local
                                name = <D <U <assignTemp>> $3>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:27:13-27:26, value = 0 }
                              ]
                            }
                          }
                        ],
                        expr = UnresolvedIdent{
                          loc = test/testdata/desugar/for.rb:27:13-27:26
                          kind = Local
                          name = <D <U <assignTemp>> $2>
                        }
                      }
                    ],
                    expr = Send{
                      loc = test/testdata/desugar/for.rb:28:13-28:27
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:28:13-28:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:28:18-28:27
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:28:18-28:19
                            kind = Local
                            name = <U a>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                  }
                }
                pos_args = 0
                args = [
                ]
              }
              Send{
                loc = test/testdata/desugar/for.rb:31:9-34:12
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/for.rb:31:20-31:21
                  cnst = <C <U A>>
                  scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                }
                fun = <U each>
                block = Block {
                  loc = test/testdata/desugar/for.rb:31:9-34:12
                  args = [
                    UnresolvedIdent{
                      loc = test/testdata/desugar/for.rb:31:13-31:14
                      kind = Local
                      name = <U a>
                    }
                    UnresolvedIdent{
                      loc = test/testdata/desugar/for.rb:31:15-31:16
                      kind = Local
                      name = <U b>
                    }
                  ]
                  body = InsSeq{
                    loc = test/testdata/desugar/for.rb:32:13-33:27
                    stats = [
                      Send{
                        loc = test/testdata/desugar/for.rb:32:13-32:27
                        flags = {privateOk}
                        recv = Local{
                          loc = test/testdata/desugar/for.rb:32:13-32:13
                          localVariable = <U <self>>
                        }
                        fun = <U puts>
                        block = nullptr
                        pos_args = 1
                        args = [
                          Send{
                            loc = test/testdata/desugar/for.rb:32:18-32:27
                            flags = {}
                            recv = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:32:18-32:19
                              kind = Local
                              name = <U a>
                            }
                            fun = <U inspect>
                            block = nullptr
                            pos_args = 0
                            args = [
                            ]
                          }
                        ]
                      }
                    ],
                    expr = Send{
                      loc = test/testdata/desugar/for.rb:33:13-33:27
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:33:13-33:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:33:18-33:27
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:33:18-33:19
                            kind = Local
                            name = <U b>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                  }
                }
                pos_args = 0
                args = [
                ]
              }
              Send{
                loc = test/testdata/desugar/for.rb:35:9-39:12
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/for.rb:35:9-35:10
                  cnst = <C <U A>>
                  scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                }
                fun = <U each>
                block = Block {
                  loc = test/testdata/desugar/for.rb:35:9-39:12
                  args = [
                    RestArg{ loc = test/testdata/desugar/for.rb:35:20-35:28, expr = UnresolvedIdent{
                      loc = test/testdata/desugar/for.rb:35:21-35:28
                      kind = Local
                      name = <U forTemp>
                    } }
                  ]
                  body = InsSeq{
                    loc = test/testdata/desugar/for.rb:36:13-38:27
                    stats = [
                      InsSeq{
                        loc = test/testdata/desugar/for.rb:36:13-36:27
                        stats = [
                          Assign{
                            loc = test/testdata/desugar/for.rb:36:13-36:27
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:36:13-36:27
                              kind = Local
                              name = <D <U <assignTemp>> $4>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:36:19-36:27
                              flags = {}
                              recv = ConstantLit{
                                loc = test/testdata/desugar/for.rb:36:19-36:27
                                symbol = (class ::<Magic>)
                                orig = nullptr
                              }
                              fun = <U <splat>>
                              block = nullptr
                              pos_args = 1
                              args = [
                                UnresolvedIdent{
                                  loc = test/testdata/desugar/for.rb:36:20-36:27
                                  kind = Local
                                  name = <U forTemp>
                                }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:36:13-36:27
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:36:13-36:27
                              kind = Local
                              name = <D <U <assignTemp>> $5>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:36:13-36:27
                              flags = {}
                              recv = ConstantLit{
                                loc = test/testdata/desugar/for.rb:36:13-36:27
                                symbol = (class ::<Magic>)
                                orig = nullptr
                              }
                              fun = <U <expand-splat>>
                              block = nullptr
                              pos_args = 3
                              args = [
                                UnresolvedIdent{
                                  loc = test/testdata/desugar/for.rb:36:13-36:27
                                  kind = Local
                                  name = <D <U <assignTemp>> $4>
                                }
                                Literal{ loc = test/testdata/desugar/for.rb:36:13-36:27, value = 2 }
                                Literal{ loc = test/testdata/desugar/for.rb:36:13-36:27, value = 0 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:36:13-36:14
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:36:13-36:14
                              kind = Local
                              name = <U a>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:36:13-36:14
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:36:13-36:14
                                kind = Local
                                name = <D <U <assignTemp>> $5>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:36:13-36:27, value = 0 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:36:15-36:16
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:36:15-36:16
                              kind = Local
                              name = <U b>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:36:15-36:16
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:36:15-36:16
                                kind = Local
                                name = <D <U <assignTemp>> $5>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:36:13-36:27, value = 1 }
                              ]
                            }
                          }
                        ],
                        expr = UnresolvedIdent{
                          loc = test/testdata/desugar/for.rb:36:13-36:27
                          kind = Local
                          name = <D <U <assignTemp>> $4>
                        }
                      }
                      Send{
                        loc = test/testdata/desugar/for.rb:37:13-37:27
                        flags = {privateOk}
                        recv = Local{
                          loc = test/testdata/desugar/for.rb:37:13-37:13
                          localVariable = <U <self>>
                        }
                        fun = <U puts>
                        block = nullptr
                        pos_args = 1
                        args = [
                          Send{
                            loc = test/testdata/desugar/for.rb:37:18-37:27
                            flags = {}
                            recv = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:37:18-37:19
                              kind = Local
                              name = <U a>
                            }
                            fun = <U inspect>
                            block = nullptr
                            pos_args = 0
                            args = [
                            ]
                          }
                        ]
                      }
                    ],
                    expr = Send{
                      loc = test/testdata/desugar/for.rb:38:13-38:27
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:38:13-38:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:38:18-38:27
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:38:18-38:19
                            kind = Local
                            name = <U b>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                  }
                }
                pos_args = 0
                args = [
                ]
              }
              Send{
                loc = test/testdata/desugar/for.rb:40:9-40:20
                flags = {privateOk}
                recv = Local{
                  loc = test/testdata/desugar/for.rb:40:9-40:9
                  localVariable = <U <self>>
                }
                fun = <U puts>
                block = nullptr
                pos_args = 1
                args = [
                  Literal{ loc = test/testdata/desugar/for.rb:40:14-40:20, value = "main" }
                ]
              }
              Send{
                loc = test/testdata/desugar/for.rb:42:9-50:12
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/for.rb:42:32-42:33
                  cnst = <C <U A>>
                  scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                }
                fun = <U each>
                block = Block {
                  loc = test/testdata/desugar/for.rb:42:9-50:12
                  args = [
                  ]
                  body = InsSeq{
                    loc = test/testdata/desugar/for.rb:42:9-50:12
                    stats = [
                      InsSeq{
                        loc = test/testdata/desugar/for.rb:42:9-50:12
                        stats = [
                          Assign{
                            loc = test/testdata/desugar/for.rb:42:9-50:12
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:9-50:12
                              kind = Local
                              name = <D <U <assignTemp>> $7>
                            }
                            rhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:9-50:12
                              kind = Local
                              name = <D <U forTemp> $6>
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:42:9-50:12
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:9-50:12
                              kind = Local
                              name = <D <U <assignTemp>> $8>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:42:9-50:12
                              flags = {}
                              recv = ConstantLit{
                                loc = test/testdata/desugar/for.rb:42:9-50:12
                                symbol = (class ::<Magic>)
                                orig = nullptr
                              }
                              fun = <U <expand-splat>>
                              block = nullptr
                              pos_args = 3
                              args = [
                                UnresolvedIdent{
                                  loc = test/testdata/desugar/for.rb:42:9-50:12
                                  kind = Local
                                  name = <D <U <assignTemp>> $7>
                                }
                                Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 5 }
                                Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 0 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:42:13-42:15
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:13-42:15
                              kind = Instance
                              name = <U @a>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:42:13-42:15
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:42:13-42:15
                                kind = Local
                                name = <D <U <assignTemp>> $8>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 0 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:42:16-42:19
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:16-42:19
                              kind = Class
                              name = <U @@b>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:42:16-42:19
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:42:16-42:19
                                kind = Local
                                name = <D <U <assignTemp>> $8>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 1 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:42:20-42:22
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:20-42:22
                              kind = Global
                              name = <U $c>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:42:20-42:22
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:42:20-42:22
                                kind = Local
                                name = <D <U <assignTemp>> $8>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 2 }
                              ]
                            }
                          }
                          Assign{
                            loc = test/testdata/desugar/for.rb:42:23-42:24
                            lhs = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:42:23-42:24
                              kind = Local
                              name = <U d>
                            }
                            rhs = Send{
                              loc = test/testdata/desugar/for.rb:42:23-42:24
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:42:23-42:24
                                kind = Local
                                name = <D <U <assignTemp>> $8>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 3 }
                              ]
                            }
                          }
                          Send{
                            loc = test/testdata/desugar/for.rb:42:25-42:28
                            flags = {}
                            recv = UnresolvedConstantLit{
                              loc = test/testdata/desugar/for.rb:42:25-42:26
                              cnst = <C <U E>>
                              scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                            }
                            fun = <U e=>
                            block = nullptr
                            pos_args = 1
                            args = [
                              Send{
                                loc = test/testdata/desugar/for.rb:42:25-42:28
                                flags = {}
                                recv = UnresolvedIdent{
                                  loc = test/testdata/desugar/for.rb:42:25-42:28
                                  kind = Local
                                  name = <D <U <assignTemp>> $8>
                                }
                                fun = <U []>
                                block = nullptr
                                pos_args = 1
                                args = [
                                  Literal{ loc = test/testdata/desugar/for.rb:42:9-50:12, value = 4 }
                                ]
                              }
                            ]
                          }
                        ],
                        expr = UnresolvedIdent{
                          loc = test/testdata/desugar/for.rb:42:9-50:12
                          kind = Local
                          name = <D <U <assignTemp>> $7>
                        }
                      }
                    ],
                    expr = InsSeq{
                      loc = test/testdata/desugar/for.rb:45:13-49:29
                      stats = [
                        Send{
                          loc = test/testdata/desugar/for.rb:45:13-45:28
                          flags = {privateOk}
                          recv = Local{
                            loc = test/testdata/desugar/for.rb:45:13-45:13
                            localVariable = <U <self>>
                          }
                          fun = <U puts>
                          block = nullptr
                          pos_args = 1
                          args = [
                            Send{
                              loc = test/testdata/desugar/for.rb:45:18-45:28
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:45:18-45:20
                                kind = Instance
                                name = <U @a>
                              }
                              fun = <U inspect>
                              block = nullptr
                              pos_args = 0
                              args = [
                              ]
                            }
                          ]
                        }
                        Send{
                          loc = test/testdata/desugar/for.rb:46:13-46:29
                          flags = {privateOk}
                          recv = Local{
                            loc = test/testdata/desugar/for.rb:46:13-46:13
                            localVariable = <U <self>>
                          }
                          fun = <U puts>
                          block = nullptr
                          pos_args = 1
                          args = [
                            Send{
                              loc = test/testdata/desugar/for.rb:46:18-46:29
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:46:18-46:21
                                kind = Class
                                name = <U @@b>
                              }
                              fun = <U inspect>
                              block = nullptr
                              pos_args = 0
                              args = [
                              ]
                            }
                          ]
                        }
                        Send{
                          loc = test/testdata/desugar/for.rb:47:13-47:28
                          flags = {privateOk}
                          recv = Local{
                            loc = test/testdata/desugar/for.rb:47:13-47:13
                            localVariable = <U <self>>
                          }
                          fun = <U puts>
                          block = nullptr
                          pos_args = 1
                          args = [
                            Send{
                              loc = test/testdata/desugar/for.rb:47:18-47:28
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:47:18-47:20
                                kind = Global
                                name = <U $c>
                              }
                              fun = <U inspect>
                              block = nullptr
                              pos_args = 0
                              args = [
                              ]
                            }
                          ]
                        }
                        Send{
                          loc = test/testdata/desugar/for.rb:48:13-48:27
                          flags = {privateOk}
                          recv = Local{
                            loc = test/testdata/desugar/for.rb:48:13-48:13
                            localVariable = <U <self>>
                          }
                          fun = <U puts>
                          block = nullptr
                          pos_args = 1
                          args = [
                            Send{
                              loc = test/testdata/desugar/for.rb:48:18-48:27
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:48:18-48:19
                                kind = Local
                                name = <U d>
                              }
                              fun = <U inspect>
                              block = nullptr
                              pos_args = 0
                              args = [
                              ]
                            }
                          ]
                        }
                      ],
                      expr = Send{
                        loc = test/testdata/desugar/for.rb:49:13-49:29
                        flags = {privateOk}
                        recv = Local{
                          loc = test/testdata/desugar/for.rb:49:13-49:13
                          localVariable = <U <self>>
                        }
                        fun = <U puts>
                        block = nullptr
                        pos_args = 1
                        args = [
                          Send{
                            loc = test/testdata/desugar/for.rb:49:18-49:29
                            flags = {}
                            recv = Send{
                              loc = test/testdata/desugar/for.rb:49:18-49:21
                              flags = {}
                              recv = UnresolvedConstantLit{
                                loc = test/testdata/desugar/for.rb:49:18-49:19
                                cnst = <C <U E>>
                                scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                              }
                              fun = <U e>
                              block = nullptr
                              pos_args = 0
                              args = [
                              ]
                            }
                            fun = <U inspect>
                            block = nullptr
                            pos_args = 0
                            args = [
                            ]
                          }
                        ]
                      }
                    }
                  }
                }
                pos_args = 0
                args = [
                ]
              }
            ],
            expr = Send{
              loc = test/testdata/desugar/for.rb:51:9-60:12
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/for.rb:51:9-51:10
                cnst = <C <U A>>
                scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
              }
              fun = <U each>
              block = Block {
                loc = test/testdata/desugar/for.rb:51:9-60:12
                args = [
                  RestArg{ loc = test/testdata/desugar/for.rb:51:20-51:28, expr = UnresolvedIdent{
                    loc = test/testdata/desugar/for.rb:51:21-51:28
                    kind = Local
                    name = <U forTemp>
                  } }
                ]
                body = InsSeq{
                  loc = test/testdata/desugar/for.rb:52:13-59:29
                  stats = [
                    InsSeq{
                      loc = test/testdata/desugar/for.rb:52:13-52:39
                      stats = [
                        Assign{
                          loc = test/testdata/desugar/for.rb:52:13-52:39
                          lhs = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:52:13-52:39
                            kind = Local
                            name = <D <U <assignTemp>> $9>
                          }
                          rhs = Send{
                            loc = test/testdata/desugar/for.rb:52:31-52:39
                            flags = {}
                            recv = ConstantLit{
                              loc = test/testdata/desugar/for.rb:52:31-52:39
                              symbol = (class ::<Magic>)
                              orig = nullptr
                            }
                            fun = <U <splat>>
                            block = nullptr
                            pos_args = 1
                            args = [
                              UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:52:32-52:39
                                kind = Local
                                name = <U forTemp>
                              }
                            ]
                          }
                        }
                        Assign{
                          loc = test/testdata/desugar/for.rb:52:13-52:39
                          lhs = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:52:13-52:39
                            kind = Local
                            name = <D <U <assignTemp>> $10>
                          }
                          rhs = Send{
                            loc = test/testdata/desugar/for.rb:52:13-52:39
                            flags = {}
                            recv = ConstantLit{
                              loc = test/testdata/desugar/for.rb:52:13-52:39
                              symbol = (class ::<Magic>)
                              orig = nullptr
                            }
                            fun = <U <expand-splat>>
                            block = nullptr
                            pos_args = 3
                            args = [
                              UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:52:13-52:39
                                kind = Local
                                name = <D <U <assignTemp>> $9>
                              }
                              Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 5 }
                              Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 0 }
                            ]
                          }
                        }
                        Assign{
                          loc = test/testdata/desugar/for.rb:52:13-52:15
                          lhs = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:52:13-52:15
                            kind = Instance
                            name = <U @a>
                          }
                          rhs = Send{
                            loc = test/testdata/desugar/for.rb:52:13-52:15
                            flags = {}
                            recv = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:52:13-52:15
                              kind = Local
                              name = <D <U <assignTemp>> $10>
                            }
                            fun = <U []>
                            block = nullptr
                            pos_args = 1
                            args = [
                              Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 0 }
                            ]
                          }
                        }
                        Assign{
                          loc = test/testdata/desugar/for.rb:52:16-52:19
                          lhs = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:52:16-52:19
                            kind = Class
                            name = <U @@b>
                          }
                          rhs = Send{
                            loc = test/testdata/desugar/for.rb:52:16-52:19
                            flags = {}
                            recv = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:52:16-52:19
                              kind = Local
                              name = <D <U <assignTemp>> $10>
                            }
                            fun = <U []>
                            block = nullptr
                            pos_args = 1
                            args = [
                              Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 1 }
                            ]
                          }
                        }
                        Assign{
                          loc = test/testdata/desugar/for.rb:52:20-52:22
                          lhs = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:52:20-52:22
                            kind = Global
                            name = <U $c>
                          }
                          rhs = Send{
                            loc = test/testdata/desugar/for.rb:52:20-52:22
                            flags = {}
                            recv = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:52:20-52:22
                              kind = Local
                              name = <D <U <assignTemp>> $10>
                            }
                            fun = <U []>
                            block = nullptr
                            pos_args = 1
                            args = [
                              Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 2 }
                            ]
                          }
                        }
                        Assign{
                          loc = test/testdata/desugar/for.rb:52:23-52:24
                          lhs = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:52:23-52:24
                            kind = Local
                            name = <U d>
                          }
                          rhs = Send{
                            loc = test/testdata/desugar/for.rb:52:23-52:24
                            flags = {}
                            recv = UnresolvedIdent{
                              loc = test/testdata/desugar/for.rb:52:23-52:24
                              kind = Local
                              name = <D <U <assignTemp>> $10>
                            }
                            fun = <U []>
                            block = nullptr
                            pos_args = 1
                            args = [
                              Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 3 }
                            ]
                          }
                        }
                        Send{
                          loc = test/testdata/desugar/for.rb:52:25-52:28
                          flags = {}
                          recv = UnresolvedConstantLit{
                            loc = test/testdata/desugar/for.rb:52:25-52:26
                            cnst = <C <U E>>
                            scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                          }
                          fun = <U e=>
                          block = nullptr
                          pos_args = 1
                          args = [
                            Send{
                              loc = test/testdata/desugar/for.rb:52:25-52:28
                              flags = {}
                              recv = UnresolvedIdent{
                                loc = test/testdata/desugar/for.rb:52:25-52:28
                                kind = Local
                                name = <D <U <assignTemp>> $10>
                              }
                              fun = <U []>
                              block = nullptr
                              pos_args = 1
                              args = [
                                Literal{ loc = test/testdata/desugar/for.rb:52:13-52:39, value = 4 }
                              ]
                            }
                          ]
                        }
                      ],
                      expr = UnresolvedIdent{
                        loc = test/testdata/desugar/for.rb:52:13-52:39
                        kind = Local
                        name = <D <U <assignTemp>> $9>
                      }
                    }
                    Send{
                      loc = test/testdata/desugar/for.rb:55:13-55:28
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:55:13-55:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:55:18-55:28
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:55:18-55:20
                            kind = Instance
                            name = <U @a>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                    Send{
                      loc = test/testdata/desugar/for.rb:56:13-56:29
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:56:13-56:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:56:18-56:29
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:56:18-56:21
                            kind = Class
                            name = <U @@b>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                    Send{
                      loc = test/testdata/desugar/for.rb:57:13-57:28
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:57:13-57:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:57:18-57:28
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:57:18-57:20
                            kind = Global
                            name = <U $c>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                    Send{
                      loc = test/testdata/desugar/for.rb:58:13-58:27
                      flags = {privateOk}
                      recv = Local{
                        loc = test/testdata/desugar/for.rb:58:13-58:13
                        localVariable = <U <self>>
                      }
                      fun = <U puts>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Send{
                          loc = test/testdata/desugar/for.rb:58:18-58:27
                          flags = {}
                          recv = UnresolvedIdent{
                            loc = test/testdata/desugar/for.rb:58:18-58:19
                            kind = Local
                            name = <U d>
                          }
                          fun = <U inspect>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                      ]
                    }
                  ],
                  expr = Send{
                    loc = test/testdata/desugar/for.rb:59:13-59:29
                    flags = {privateOk}
                    recv = Local{
                      loc = test/testdata/desugar/for.rb:59:13-59:13
                      localVariable = <U <self>>
                    }
                    fun = <U puts>
                    block = nullptr
                    pos_args = 1
                    args = [
                      Send{
                        loc = test/testdata/desugar/for.rb:59:18-59:29
                        flags = {}
                        recv = Send{
                          loc = test/testdata/desugar/for.rb:59:18-59:21
                          flags = {}
                          recv = UnresolvedConstantLit{
                            loc = test/testdata/desugar/for.rb:59:18-59:19
                            cnst = <C <U E>>
                            scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
                          }
                          fun = <U e>
                          block = nullptr
                          pos_args = 0
                          args = [
                          ]
                        }
                        fun = <U inspect>
                        block = nullptr
                        pos_args = 0
                        args = [
                        ]
                      }
                    ]
                  }
                }
              }
              pos_args = 0
              args = [
              ]
            }
          }
        }
      ]
    }

    Send{
      loc = test/testdata/desugar/for.rb:63:1-63:10
      flags = {}
      recv = UnresolvedConstantLit{
        loc = test/testdata/desugar/for.rb:63:1-63:5
        cnst = <C <U Main>>
        scope = EmptyTree{ loc = test/testdata/desugar/for.rb }
      }
      fun = <U main>
      block = nullptr
      pos_args = 0
      args = [
      ]
    }
  ]
}
