ClassDef{
  loc = test/testdata/desugar/keyword_args.rb:3:1-30:22
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/keyword_args.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/keyword_args.rb:3:1-30:22
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    MethodDef{
      loc = test/testdata/desugar/keyword_args.rb:3:1-6:4
      flags = {}
      name = <U foo><<U <todo method>>>
      args = [KeywordArg{ loc = test/testdata/desugar/keyword_args.rb:3:9-3:11, expr = UnresolvedIdent{
          loc = test/testdata/desugar/keyword_args.rb:3:9-3:11
          kind = Local
          name = <U x>
        } }, OptionalArg{
          loc = test/testdata/desugar/keyword_args.rb:3:13-3:18
          expr = KeywordArg{ loc = test/testdata/desugar/keyword_args.rb:3:13-3:15, expr = UnresolvedIdent{
            loc = test/testdata/desugar/keyword_args.rb:3:13-3:15
            kind = Local
            name = <U y>
          } }
          default_ = Literal{ loc = test/testdata/desugar/keyword_args.rb:3:16-3:18, value = 10 }
        }, BlockArg{ loc = test/testdata/desugar/keyword_args.rb, expr = UnresolvedIdent{
          loc = test/testdata/desugar/keyword_args.rb
          kind = Local
          name = <U <blk>>
        } }]
      rhs = InsSeq{
        loc = test/testdata/desugar/keyword_args.rb:4:3-5:6
        stats = [
          Send{
            loc = test/testdata/desugar/keyword_args.rb:4:3-4:6
            flags = {privateOk}
            recv = Local{
              loc = test/testdata/desugar/keyword_args.rb:4:3-4:3
              localVariable = <U <self>>
            }
            fun = <U p>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:4:5-4:6
                kind = Local
                name = <U x>
              }
            ]
          }
        ],
        expr = Send{
          loc = test/testdata/desugar/keyword_args.rb:5:3-5:6
          flags = {privateOk}
          recv = Local{
            loc = test/testdata/desugar/keyword_args.rb:5:3-5:3
            localVariable = <U <self>>
          }
          fun = <U p>
          block = nullptr
          pos_args = 1
          args = [
            UnresolvedIdent{
              loc = test/testdata/desugar/keyword_args.rb:5:5-5:6
              kind = Local
              name = <U y>
            }
          ]
        }
      }
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:8:1-8:11
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:8:1-8:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        Literal{ loc = test/testdata/desugar/keyword_args.rb:8:5-8:6, value = :x }
        Literal{ loc = test/testdata/desugar/keyword_args.rb:8:8-8:10, value = 10 }
      ]
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:9:1-9:18
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:9:1-9:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        Literal{ loc = test/testdata/desugar/keyword_args.rb:9:5-9:6, value = :x }
        Literal{ loc = test/testdata/desugar/keyword_args.rb:9:8-9:10, value = 10 }
        Literal{ loc = test/testdata/desugar/keyword_args.rb:9:12-9:13, value = :y }
        Literal{ loc = test/testdata/desugar/keyword_args.rb:9:15-9:17, value = 20 }
      ]
    }

    Assign{
      loc = test/testdata/desugar/keyword_args.rb:11:1-11:15
      lhs = UnresolvedIdent{
        loc = test/testdata/desugar/keyword_args.rb:11:1-11:5
        kind = Local
        name = <U args>
      }
      rhs = Hash{
        loc = test/testdata/desugar/keyword_args.rb:11:8-11:15
        pairs = [
          [
            key = Literal{ loc = test/testdata/desugar/keyword_args.rb:11:9-11:10, value = :x }
            value = Literal{ loc = test/testdata/desugar/keyword_args.rb:11:12-11:14, value = 10 }
          ]
        ]
      }
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:12:1-12:12
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:12:1-12:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        InsSeq{
          loc = test/testdata/desugar/keyword_args.rb:12:5-12:11
          stats = [
            Assign{
              loc = test/testdata/desugar/keyword_args.rb:12:5-12:11
              lhs = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:12:5-12:11
                kind = Local
                name = <D <U <hashTemp>> $3>
              }
              rhs = Send{
                loc = test/testdata/desugar/keyword_args.rb:12:5-12:11
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/keyword_args.rb:12:5-12:11
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <to-hash-dup>>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedIdent{
                    loc = test/testdata/desugar/keyword_args.rb:12:7-12:11
                    kind = Local
                    name = <U args>
                  }
                ]
              }
            }
          ],
          expr = UnresolvedIdent{
            loc = test/testdata/desugar/keyword_args.rb:12:5-12:11
            kind = Local
            name = <D <U <hashTemp>> $3>
          }
        }
      ]
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:13:1-13:19
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:13:1-13:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        InsSeq{
          loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
          stats = [
            Assign{
              loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
              lhs = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                kind = Local
                name = <D <U <hashTemp>> $4>
              }
              rhs = Hash{
                loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                pairs = [
                  [
                    key = Literal{ loc = test/testdata/desugar/keyword_args.rb:13:5-13:6, value = :x }
                    value = Literal{ loc = test/testdata/desugar/keyword_args.rb:13:8-13:10, value = 20 }
                  ]
                ]
              }
            }
            Assign{
              loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
              lhs = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                kind = Local
                name = <D <U <hashTemp>> $4>
              }
              rhs = Send{
                loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <merge-hash>>
                block = nullptr
                pos_args = 2
                args = [
                  UnresolvedIdent{
                    loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                    kind = Local
                    name = <D <U <hashTemp>> $4>
                  }
                  Send{
                    loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                    flags = {}
                    recv = ConstantLit{
                      loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
                      symbol = (class ::<Magic>)
                      orig = nullptr
                    }
                    fun = <U <to-hash-nodup>>
                    block = nullptr
                    pos_args = 1
                    args = [
                      UnresolvedIdent{
                        loc = test/testdata/desugar/keyword_args.rb:13:14-13:18
                        kind = Local
                        name = <U args>
                      }
                    ]
                  }
                ]
              }
            }
          ],
          expr = UnresolvedIdent{
            loc = test/testdata/desugar/keyword_args.rb:13:5-13:18
            kind = Local
            name = <D <U <hashTemp>> $4>
          }
        }
      ]
    }

    Assign{
      loc = test/testdata/desugar/keyword_args.rb:15:1-15:11
      lhs = UnresolvedIdent{
        loc = test/testdata/desugar/keyword_args.rb:15:1-15:7
        kind = Local
        name = <U other1>
      }
      rhs = Literal{ loc = test/testdata/desugar/keyword_args.rb:15:9-15:11, value = 10 }
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:16:1-16:18
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:16:1-16:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 1
      args = [
        Hash{
          loc = test/testdata/desugar/keyword_args.rb:16:5-16:17
          pairs = [
            [
              key = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:16:5-16:11
                kind = Local
                name = <U other1>
              }
              value = Literal{ loc = test/testdata/desugar/keyword_args.rb:16:15-16:17, value = 10 }
            ]
          ]
        }
      ]
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:18:1-18:22
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:18:1-18:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        InsSeq{
          loc = test/testdata/desugar/keyword_args.rb:18:5-18:21
          stats = [
            Assign{
              loc = test/testdata/desugar/keyword_args.rb:18:5-18:21
              lhs = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:18:5-18:21
                kind = Local
                name = <D <U <hashTemp>> $6>
              }
              rhs = Send{
                loc = test/testdata/desugar/keyword_args.rb:18:5-18:21
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/keyword_args.rb:18:5-18:21
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <to-hash-dup>>
                block = nullptr
                pos_args = 1
                args = [
                  Hash{
                    loc = test/testdata/desugar/keyword_args.rb:18:7-18:21
                    pairs = [
                      [
                        key = UnresolvedIdent{
                          loc = test/testdata/desugar/keyword_args.rb:18:8-18:14
                          kind = Local
                          name = <U other1>
                        }
                        value = Literal{ loc = test/testdata/desugar/keyword_args.rb:18:18-18:20, value = 10 }
                      ]
                    ]
                  }
                ]
              }
            }
          ],
          expr = UnresolvedIdent{
            loc = test/testdata/desugar/keyword_args.rb:18:5-18:21
            kind = Local
            name = <D <U <hashTemp>> $6>
          }
        }
      ]
    }

    Assign{
      loc = test/testdata/desugar/keyword_args.rb:21:1-21:15
      lhs = UnresolvedIdent{
        loc = test/testdata/desugar/keyword_args.rb:21:1-21:7
        kind = Local
        name = <U other2>
      }
      rhs = Literal{ loc = test/testdata/desugar/keyword_args.rb:21:10-21:15, value = "foo" }
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:22:1-22:18
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:22:1-22:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 1
      args = [
        Hash{
          loc = test/testdata/desugar/keyword_args.rb:22:5-22:17
          pairs = [
            [
              key = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:22:5-22:11
                kind = Local
                name = <U other2>
              }
              value = Literal{ loc = test/testdata/desugar/keyword_args.rb:22:15-22:17, value = 10 }
            ]
          ]
        }
      ]
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:24:1-24:22
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:24:1-24:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        InsSeq{
          loc = test/testdata/desugar/keyword_args.rb:24:5-24:21
          stats = [
            Assign{
              loc = test/testdata/desugar/keyword_args.rb:24:5-24:21
              lhs = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:24:5-24:21
                kind = Local
                name = <D <U <hashTemp>> $9>
              }
              rhs = Send{
                loc = test/testdata/desugar/keyword_args.rb:24:5-24:21
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/keyword_args.rb:24:5-24:21
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <to-hash-dup>>
                block = nullptr
                pos_args = 1
                args = [
                  Hash{
                    loc = test/testdata/desugar/keyword_args.rb:24:7-24:21
                    pairs = [
                      [
                        key = UnresolvedIdent{
                          loc = test/testdata/desugar/keyword_args.rb:24:8-24:14
                          kind = Local
                          name = <U other2>
                        }
                        value = Literal{ loc = test/testdata/desugar/keyword_args.rb:24:18-24:20, value = 10 }
                      ]
                    ]
                  }
                ]
              }
            }
          ],
          expr = UnresolvedIdent{
            loc = test/testdata/desugar/keyword_args.rb:24:5-24:21
            kind = Local
            name = <D <U <hashTemp>> $9>
          }
        }
      ]
    }

    Assign{
      loc = test/testdata/desugar/keyword_args.rb:27:1-27:29
      lhs = UnresolvedIdent{
        loc = test/testdata/desugar/keyword_args.rb:27:1-27:7
        kind = Local
        name = <U other3>
      }
      rhs = Send{
        loc = test/testdata/desugar/keyword_args.rb:27:10-27:29
        flags = {}
        recv = UnresolvedConstantLit{
          loc = test/testdata/desugar/keyword_args.rb:27:10-27:11
          cnst = <C <U T>>
          scope = EmptyTree{ loc = test/testdata/desugar/keyword_args.rb }
        }
        fun = <U let>
        block = nullptr
        pos_args = 2
        args = [
          Literal{ loc = test/testdata/desugar/keyword_args.rb:27:16-27:20, value = :foo }
          UnresolvedConstantLit{
            loc = test/testdata/desugar/keyword_args.rb:27:22-27:28
            cnst = <C <U Symbol>>
            scope = EmptyTree{ loc = test/testdata/desugar/keyword_args.rb }
          }
        ]
      }
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:28:1-28:18
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:28:1-28:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 1
      args = [
        Hash{
          loc = test/testdata/desugar/keyword_args.rb:28:5-28:17
          pairs = [
            [
              key = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:28:5-28:11
                kind = Local
                name = <U other3>
              }
              value = Literal{ loc = test/testdata/desugar/keyword_args.rb:28:15-28:17, value = 10 }
            ]
          ]
        }
      ]
    }

    Send{
      loc = test/testdata/desugar/keyword_args.rb:30:1-30:22
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/keyword_args.rb:30:1-30:1
        localVariable = <U <self>>
      }
      fun = <U foo>
      block = nullptr
      pos_args = 0
      args = [
        InsSeq{
          loc = test/testdata/desugar/keyword_args.rb:30:5-30:21
          stats = [
            Assign{
              loc = test/testdata/desugar/keyword_args.rb:30:5-30:21
              lhs = UnresolvedIdent{
                loc = test/testdata/desugar/keyword_args.rb:30:5-30:21
                kind = Local
                name = <D <U <hashTemp>> $12>
              }
              rhs = Send{
                loc = test/testdata/desugar/keyword_args.rb:30:5-30:21
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/keyword_args.rb:30:5-30:21
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <to-hash-dup>>
                block = nullptr
                pos_args = 1
                args = [
                  Hash{
                    loc = test/testdata/desugar/keyword_args.rb:30:7-30:21
                    pairs = [
                      [
                        key = UnresolvedIdent{
                          loc = test/testdata/desugar/keyword_args.rb:30:8-30:14
                          kind = Local
                          name = <U other3>
                        }
                        value = Literal{ loc = test/testdata/desugar/keyword_args.rb:30:18-30:20, value = 10 }
                      ]
                    ]
                  }
                ]
              }
            }
          ],
          expr = UnresolvedIdent{
            loc = test/testdata/desugar/keyword_args.rb:30:5-30:21
            kind = Local
            name = <D <U <hashTemp>> $12>
          }
        }
      ]
    }
  ]
}
