ClassDef{
  loc = test/testdata/desugar/pattern_matching_assign.rb:3:1-25:17
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/pattern_matching_assign.rb:3:1-25:17
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    Assign{
      loc = test/testdata/desugar/pattern_matching_assign.rb:3:1-3:11
      lhs = UnresolvedIdent{
        loc = test/testdata/desugar/pattern_matching_assign.rb:3:1-3:5
        kind = Local
        name = <U expr>
      }
      rhs = Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:3:8-3:11, value = "x" }
    }

    Send{
      loc = test/testdata/desugar/pattern_matching_assign.rb:4:1-4:20
      flags = {}
      recv = UnresolvedConstantLit{
        loc = test/testdata/desugar/pattern_matching_assign.rb:4:1-4:2
        cnst = <C <U T>>
        scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
      }
      fun = <U reveal_type>
      block = nullptr
      pos_args = 1
      args = [
        UnresolvedIdent{
          loc = test/testdata/desugar/pattern_matching_assign.rb:4:15-4:19
          kind = Local
          name = <U expr>
        }
      ]
    }

    Assign{
      loc = test/testdata/desugar/pattern_matching_assign.rb:6:1-23:4
      lhs = UnresolvedIdent{
        loc = test/testdata/desugar/pattern_matching_assign.rb:6:1-6:2
        kind = Local
        name = <U x>
      }
      rhs = InsSeq{
        loc = test/testdata/desugar/pattern_matching_assign.rb:6:5-23:4
        stats = [
          Assign{
            loc = test/testdata/desugar/pattern_matching_assign.rb:6:10-6:14
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/pattern_matching_assign.rb:6:10-6:14
              kind = Local
              name = <D <U <assignTemp>> $2>
            }
            rhs = UnresolvedIdent{
              loc = test/testdata/desugar/pattern_matching_assign.rb:6:10-6:14
              kind = Local
              name = <U expr>
            }
          }
        ],
        expr = If{
          loc = test/testdata/desugar/pattern_matching_assign.rb:7:1-9:4
          cond = Send{
            loc = test/testdata/desugar/pattern_matching_assign.rb:7:4-7:12
            flags = {rewriterSynthesized}
            recv = Send{
              loc = test/testdata/desugar/pattern_matching_assign.rb:7:4-7:12
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/pattern_matching_assign.rb:7:4-7:12
                symbol = (module ::T)
                orig = nullptr
              }
              fun = <U unsafe>
              block = nullptr
              pos_args = 1
              args = [
                ConstantLit{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:7:4-7:12
                  symbol = (module ::Kernel)
                  orig = nullptr
                }
              ]
            }
            fun = <U raise>
            block = nullptr
            pos_args = 1
            args = [
              Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:7:4-7:12, value = "Sorbet rewriter pass partially unimplemented" }
            ]
          }
          thenp = InsSeq{
            loc = test/testdata/desugar/pattern_matching_assign.rb:7:4-7:12
            stats = [
              Assign{
                loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12
                lhs = UnresolvedIdent{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12
                  kind = Local
                  name = <U s>
                }
                rhs = Send{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12
                  flags = {rewriterSynthesized}
                  recv = Send{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12
                    flags = {}
                    recv = ConstantLit{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12
                      symbol = (module ::T)
                      orig = nullptr
                    }
                    fun = <U unsafe>
                    block = nullptr
                    pos_args = 1
                    args = [
                      ConstantLit{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12
                        symbol = (module ::Kernel)
                        orig = nullptr
                      }
                    ]
                  }
                  fun = <U raise>
                  block = nullptr
                  pos_args = 1
                  args = [
                    Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:7:11-7:12, value = "Sorbet rewriter pass partially unimplemented" }
                  ]
                }
              }
            ],
            expr = InsSeq{
              loc = test/testdata/desugar/pattern_matching_assign.rb:8:1-9:4
              stats = [
                Send{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:8:1-8:17
                  flags = {}
                  recv = UnresolvedConstantLit{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:8:1-8:2
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
                  }
                  fun = <U reveal_type>
                  block = nullptr
                  pos_args = 1
                  args = [
                    UnresolvedIdent{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:8:15-8:16
                      kind = Local
                      name = <U s>
                    }
                  ]
                }
              ],
              expr = Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:9:3-9:4, value = 1 }
            }
          }
          elsep = If{
            loc = test/testdata/desugar/pattern_matching_assign.rb:10:1-12:4
            cond = Send{
              loc = test/testdata/desugar/pattern_matching_assign.rb:10:4-10:12
              flags = {rewriterSynthesized}
              recv = Send{
                loc = test/testdata/desugar/pattern_matching_assign.rb:10:4-10:12
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:10:4-10:12
                  symbol = (module ::T)
                  orig = nullptr
                }
                fun = <U unsafe>
                block = nullptr
                pos_args = 1
                args = [
                  ConstantLit{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:10:4-10:12
                    symbol = (module ::Kernel)
                    orig = nullptr
                  }
                ]
              }
              fun = <U raise>
              block = nullptr
              pos_args = 1
              args = [
                Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:10:4-10:12, value = "Sorbet rewriter pass partially unimplemented" }
              ]
            }
            thenp = InsSeq{
              loc = test/testdata/desugar/pattern_matching_assign.rb:10:4-10:12
              stats = [
                Assign{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12
                  lhs = UnresolvedIdent{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12
                    kind = Local
                    name = <U x>
                  }
                  rhs = Send{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12
                    flags = {rewriterSynthesized}
                    recv = Send{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12
                      flags = {}
                      recv = ConstantLit{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12
                        symbol = (module ::T)
                        orig = nullptr
                      }
                      fun = <U unsafe>
                      block = nullptr
                      pos_args = 1
                      args = [
                        ConstantLit{
                          loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12
                          symbol = (module ::Kernel)
                          orig = nullptr
                        }
                      ]
                    }
                    fun = <U raise>
                    block = nullptr
                    pos_args = 1
                    args = [
                      Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:10:11-10:12, value = "Sorbet rewriter pass partially unimplemented" }
                    ]
                  }
                }
              ],
              expr = InsSeq{
                loc = test/testdata/desugar/pattern_matching_assign.rb:11:3-12:4
                stats = [
                  Send{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:11:3-11:19
                    flags = {}
                    recv = UnresolvedConstantLit{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:11:3-11:4
                      cnst = <C <U T>>
                      scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
                    }
                    fun = <U reveal_type>
                    block = nullptr
                    pos_args = 1
                    args = [
                      UnresolvedIdent{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:11:17-11:18
                        kind = Local
                        name = <U x>
                      }
                    ]
                  }
                ],
                expr = Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:12:3-12:4, value = 1 }
              }
            }
            elsep = If{
              loc = test/testdata/desugar/pattern_matching_assign.rb:13:1-15:4
              cond = Send{
                loc = test/testdata/desugar/pattern_matching_assign.rb:13:4-13:15
                flags = {rewriterSynthesized}
                recv = Send{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:13:4-13:15
                  flags = {}
                  recv = ConstantLit{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:13:4-13:15
                    symbol = (module ::T)
                    orig = nullptr
                  }
                  fun = <U unsafe>
                  block = nullptr
                  pos_args = 1
                  args = [
                    ConstantLit{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:13:4-13:15
                      symbol = (module ::Kernel)
                      orig = nullptr
                    }
                  ]
                }
                fun = <U raise>
                block = nullptr
                pos_args = 1
                args = [
                  Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:13:4-13:15, value = "Sorbet rewriter pass partially unimplemented" }
                ]
              }
              thenp = InsSeq{
                loc = test/testdata/desugar/pattern_matching_assign.rb:13:4-13:15
                stats = [
                  Assign{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15
                    lhs = UnresolvedIdent{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15
                      kind = Local
                      name = <U expr>
                    }
                    rhs = Send{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15
                      flags = {rewriterSynthesized}
                      recv = Send{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15
                        flags = {}
                        recv = ConstantLit{
                          loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15
                          symbol = (module ::T)
                          orig = nullptr
                        }
                        fun = <U unsafe>
                        block = nullptr
                        pos_args = 1
                        args = [
                          ConstantLit{
                            loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15
                            symbol = (module ::Kernel)
                            orig = nullptr
                          }
                        ]
                      }
                      fun = <U raise>
                      block = nullptr
                      pos_args = 1
                      args = [
                        Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:13:11-13:15, value = "Sorbet rewriter pass partially unimplemented" }
                      ]
                    }
                  }
                ],
                expr = InsSeq{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:14:3-15:4
                  stats = [
                    Send{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:14:3-14:22
                      flags = {}
                      recv = UnresolvedConstantLit{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:14:3-14:4
                        cnst = <C <U T>>
                        scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
                      }
                      fun = <U reveal_type>
                      block = nullptr
                      pos_args = 1
                      args = [
                        UnresolvedIdent{
                          loc = test/testdata/desugar/pattern_matching_assign.rb:14:17-14:21
                          kind = Local
                          name = <U expr>
                        }
                      ]
                    }
                  ],
                  expr = Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:15:3-15:4, value = 1 }
                }
              }
              elsep = If{
                loc = test/testdata/desugar/pattern_matching_assign.rb:16:1-20:4
                cond = Send{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:16:4-16:7
                  flags = {rewriterSynthesized}
                  recv = Send{
                    loc = test/testdata/desugar/pattern_matching_assign.rb:16:4-16:7
                    flags = {}
                    recv = ConstantLit{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:16:4-16:7
                      symbol = (module ::T)
                      orig = nullptr
                    }
                    fun = <U unsafe>
                    block = nullptr
                    pos_args = 1
                    args = [
                      ConstantLit{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:16:4-16:7
                        symbol = (module ::Kernel)
                        orig = nullptr
                      }
                    ]
                  }
                  fun = <U raise>
                  block = nullptr
                  pos_args = 1
                  args = [
                    Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:16:4-16:7, value = "Sorbet rewriter pass partially unimplemented" }
                  ]
                }
                thenp = InsSeq{
                  loc = test/testdata/desugar/pattern_matching_assign.rb:18:3-20:4
                  stats = [
                    Send{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:18:3-18:19
                      flags = {}
                      recv = UnresolvedConstantLit{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:18:3-18:4
                        cnst = <C <U T>>
                        scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
                      }
                      fun = <U reveal_type>
                      block = nullptr
                      pos_args = 1
                      args = [
                        UnresolvedIdent{
                          loc = test/testdata/desugar/pattern_matching_assign.rb:18:17-18:18
                          kind = Local
                          name = <U x>
                        }
                      ]
                    }
                    Send{
                      loc = test/testdata/desugar/pattern_matching_assign.rb:19:3-19:22
                      flags = {}
                      recv = UnresolvedConstantLit{
                        loc = test/testdata/desugar/pattern_matching_assign.rb:19:3-19:4
                        cnst = <C <U T>>
                        scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
                      }
                      fun = <U reveal_type>
                      block = nullptr
                      pos_args = 1
                      args = [
                        UnresolvedIdent{
                          loc = test/testdata/desugar/pattern_matching_assign.rb:19:17-19:21
                          kind = Local
                          name = <U expr>
                        }
                      ]
                    }
                  ],
                  expr = Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:20:3-20:4, value = 1 }
                }
                elsep = Literal{ loc = test/testdata/desugar/pattern_matching_assign.rb:22:3-22:4, value = 1 }
              }
            }
          }
        }
      }
    }

    Send{
      loc = test/testdata/desugar/pattern_matching_assign.rb:25:1-25:17
      flags = {}
      recv = UnresolvedConstantLit{
        loc = test/testdata/desugar/pattern_matching_assign.rb:25:1-25:2
        cnst = <C <U T>>
        scope = EmptyTree{ loc = test/testdata/desugar/pattern_matching_assign.rb }
      }
      fun = <U reveal_type>
      block = nullptr
      pos_args = 1
      args = [
        UnresolvedIdent{
          loc = test/testdata/desugar/pattern_matching_assign.rb:25:15-25:16
          kind = Local
          name = <U x>
        }
      ]
    }
  ]
}
