ClassDef{
  loc = test/testdata/desugar/range.rb:2:1-170:4
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/range.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/range.rb:2:1-170:4
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    MethodDef{
      loc = test/testdata/desugar/range.rb:2:1-170:4
      flags = {}
      name = <U foo><<U <todo method>>>
      args = [BlockArg{ loc = test/testdata/desugar/range.rb, expr = UnresolvedIdent{
          loc = test/testdata/desugar/range.rb
          kind = Local
          name = <U <blk>>
        } }]
      rhs = InsSeq{
        loc = test/testdata/desugar/range.rb:3:3-169:25
        stats = [
          Assign{
            loc = test/testdata/desugar/range.rb:3:3-3:33
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:3:3-3:10
              kind = Local
              name = <U untyped>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:3:13-3:33
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:3:13-3:14
                cnst = <C <U T>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U let>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:3:19-3:21, value = 42 }
                Send{
                  loc = test/testdata/desugar/range.rb:3:23-3:32
                  flags = {}
                  recv = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:3:23-3:24
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                  fun = <U untyped>
                  block = nullptr
                  pos_args = 0
                  args = [
                  ]
                }
              ]
            }
          }
          Assign{
            loc = test/testdata/desugar/range.rb:4:3-4:42
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:4:3-4:10
              kind = Local
              name = <U nilable>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:4:13-4:42
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:4:13-4:14
                cnst = <C <U T>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U let>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:4:19-4:21, value = 42 }
                Send{
                  loc = test/testdata/desugar/range.rb:4:23-4:41
                  flags = {}
                  recv = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:4:23-4:24
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                  fun = <U nilable>
                  block = nullptr
                  pos_args = 1
                  args = [
                    UnresolvedConstantLit{
                      loc = test/testdata/desugar/range.rb:4:33-4:40
                      cnst = <C <U Integer>>
                      scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                    }
                  ]
                }
              ]
            }
          }
          Assign{
            loc = test/testdata/desugar/range.rb:8:3-8:13
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:8:3-8:6
              kind = Local
              name = <U lr1>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:8:9-8:13
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:8:9-8:13
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:8:9-8:10, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:8:12-8:13, value = 2 }
                Literal{ loc = test/testdata/desugar/range.rb:8:9-8:13, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:9:3-9:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:9:3-9:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:9:17-9:20
                kind = Local
                name = <U lr1>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:11:3-11:14
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:11:3-11:6
              kind = Local
              name = <U lr2>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:11:9-11:14
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:11:9-11:14
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:11:9-11:10, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:11:13-11:14, value = 2 }
                Literal{ loc = test/testdata/desugar/range.rb:11:9-11:14, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:12:3-12:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:12:3-12:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:12:17-12:20
                kind = Local
                name = <U lr2>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:14:3-14:15
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:14:3-14:6
              kind = Local
              name = <U lr3>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:14:9-14:15
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:14:9-14:15
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:14:9-14:10, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:14:12-14:15, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:14:9-14:15, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:15:3-15:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:15:3-15:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:15:17-15:20
                kind = Local
                name = <U lr3>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:17:3-17:16
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:17:3-17:6
              kind = Local
              name = <U lr4>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:17:9-17:16
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:17:9-17:16
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:17:9-17:10, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:17:13-17:16, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:17:9-17:16, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:18:3-18:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:18:3-18:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:18:17-18:20
                kind = Local
                name = <U lr4>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:20:3-20:14
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:20:3-20:6
              kind = Local
              name = <U lr5>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:20:10-20:13
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:20:10-20:13
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:20:10-20:11, value = 1 }
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                Literal{ loc = test/testdata/desugar/range.rb:20:10-20:13, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:21:3-21:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:21:3-21:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:21:17-21:20
                kind = Local
                name = <U lr5>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:23:3-23:15
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:23:3-23:6
              kind = Local
              name = <U lr6>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:23:10-23:14
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:23:10-23:14
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:23:10-23:11, value = 1 }
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                Literal{ loc = test/testdata/desugar/range.rb:23:10-23:14, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:24:3-24:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:24:3-24:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:24:17-24:20
                kind = Local
                name = <U lr6>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:26:3-26:17
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:26:3-26:6
              kind = Local
              name = <U lr7>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:26:10-26:16
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:26:10-26:16
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:26:10-26:11, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:26:13-26:16, value = "a" }
                Literal{ loc = test/testdata/desugar/range.rb:26:10-26:16, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:27:3-27:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:27:3-27:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:27:17-27:20
                kind = Local
                name = <U lr7>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:29:3-29:16
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:29:3-29:6
              kind = Local
              name = <U lr8>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:29:9-29:16
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:29:9-29:16
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:29:9-29:12, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:29:14-29:16, value = 42 }
                Literal{ loc = test/testdata/desugar/range.rb:29:9-29:16, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:30:3-30:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:30:3-30:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:30:17-30:20
                kind = Local
                name = <U lr8>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:32:3-32:17
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:32:3-32:6
              kind = Local
              name = <U lr9>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:32:9-32:17
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:32:9-32:17
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:32:9-32:12, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:32:15-32:17, value = 42 }
                Literal{ loc = test/testdata/desugar/range.rb:32:9-32:17, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:33:3-33:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:33:3-33:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:33:17-33:20
                kind = Local
                name = <U lr9>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:35:3-35:17
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:35:3-35:7
              kind = Local
              name = <U lr10>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:35:11-35:16
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:35:11-35:16
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:35:11-35:14, value = nil }
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                Literal{ loc = test/testdata/desugar/range.rb:35:11-35:16, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:36:3-36:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:36:3-36:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:36:17-36:21
                kind = Local
                name = <U lr10>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:38:3-38:18
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:38:3-38:7
              kind = Local
              name = <U lr11>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:38:11-38:17
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:38:11-38:17
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:38:11-38:14, value = nil }
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                Literal{ loc = test/testdata/desugar/range.rb:38:11-38:17, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:39:3-39:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:39:3-39:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:39:17-39:21
                kind = Local
                name = <U lr11>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:41:3-41:18
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:41:3-41:7
              kind = Local
              name = <U lr12>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:41:10-41:18
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:41:10-41:18
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:41:10-41:13, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:41:15-41:18, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:41:10-41:18, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:42:3-42:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:42:3-42:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:42:17-42:21
                kind = Local
                name = <U lr12>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:44:3-44:19
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:44:3-44:7
              kind = Local
              name = <U lr13>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:44:10-44:19
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:44:10-44:19
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:44:10-44:13, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:44:16-44:19, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:44:10-44:19, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:45:3-45:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:45:3-45:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:45:17-45:21
                kind = Local
                name = <U lr13>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:47:3-47:21
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:47:3-47:7
              kind = Local
              name = <U lr14>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:47:10-47:21
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:47:10-47:21
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:47:10-47:17
                  kind = Local
                  name = <U untyped>
                }
                Literal{ loc = test/testdata/desugar/range.rb:47:19-47:21, value = 42 }
                Literal{ loc = test/testdata/desugar/range.rb:47:10-47:21, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:48:3-48:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:48:3-48:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:48:17-48:21
                kind = Local
                name = <U lr14>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:50:3-50:20
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:50:3-50:7
              kind = Local
              name = <U lr15>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:50:10-50:20
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:50:10-50:20
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:50:10-50:11, value = 1 }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:50:13-50:20
                  kind = Local
                  name = <U untyped>
                }
                Literal{ loc = test/testdata/desugar/range.rb:50:10-50:20, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:51:3-51:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:51:3-51:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:51:17-51:21
                kind = Local
                name = <U lr15>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:53:3-53:26
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:53:3-53:7
              kind = Local
              name = <U lr16>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:53:10-53:26
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:53:10-53:26
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:53:10-53:17
                  kind = Local
                  name = <U untyped>
                }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:53:19-53:26
                  kind = Local
                  name = <U untyped>
                }
                Literal{ loc = test/testdata/desugar/range.rb:53:10-53:26, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:54:3-54:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:54:3-54:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:54:17-54:21
                kind = Local
                name = <U lr16>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:56:3-56:20
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:56:3-56:7
              kind = Local
              name = <U lr17>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:56:10-56:20
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:56:10-56:20
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:56:10-56:11, value = 1 }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:56:13-56:20
                  kind = Local
                  name = <U nilable>
                }
                Literal{ loc = test/testdata/desugar/range.rb:56:10-56:20, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:57:3-57:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:57:3-57:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:57:17-57:21
                kind = Local
                name = <U lr17>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:59:3-59:20
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:59:3-59:7
              kind = Local
              name = <U lr18>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:59:10-59:20
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:59:10-59:20
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:59:10-59:17
                  kind = Local
                  name = <U nilable>
                }
                Literal{ loc = test/testdata/desugar/range.rb:59:19-59:20, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:59:10-59:20, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:60:3-60:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:60:3-60:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:60:17-60:21
                kind = Local
                name = <U lr18>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:62:3-62:26
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:62:3-62:7
              kind = Local
              name = <U lr19>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:62:10-62:26
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:62:10-62:26
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:62:10-62:17
                  kind = Local
                  name = <U nilable>
                }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:62:19-62:26
                  kind = Local
                  name = <U nilable>
                }
                Literal{ loc = test/testdata/desugar/range.rb:62:10-62:26, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:63:3-63:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:63:3-63:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:63:17-63:21
                kind = Local
                name = <U lr19>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:65:3-65:15
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:65:3-65:7
              kind = Local
              name = <U lr20>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:65:11-65:14
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:65:11-65:14
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                Literal{ loc = test/testdata/desugar/range.rb:65:13-65:14, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:65:11-65:14, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:66:3-66:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:66:3-66:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:66:17-66:21
                kind = Local
                name = <U lr20>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:68:3-68:17
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:68:3-68:7
              kind = Local
              name = <U lr21>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:68:11-68:16
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:68:11-68:16
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                Literal{ loc = test/testdata/desugar/range.rb:68:13-68:16, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:68:11-68:16, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:69:3-69:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:69:3-69:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:69:17-69:21
                kind = Local
                name = <U lr21>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:71:3-71:21
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:71:3-71:7
              kind = Local
              name = <U lr22>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:71:11-71:20
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:71:11-71:20
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:71:13-71:20
                  kind = Local
                  name = <U untyped>
                }
                Literal{ loc = test/testdata/desugar/range.rb:71:11-71:20, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:72:3-72:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:72:3-72:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:72:17-72:21
                kind = Local
                name = <U lr22>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:74:3-74:21
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:74:3-74:7
              kind = Local
              name = <U lr23>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:74:11-74:20
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/range.rb:74:11-74:20
                symbol = (class ::<Magic>)
                orig = nullptr
              }
              fun = <U <build-range>>
              block = nullptr
              pos_args = 3
              args = [
                EmptyTree{ loc = test/testdata/desugar/range.rb }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:74:13-74:20
                  kind = Local
                  name = <U nilable>
                }
                Literal{ loc = test/testdata/desugar/range.rb:74:11-74:20, value = false }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:75:3-75:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:75:3-75:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:75:17-75:21
                kind = Local
                name = <U lr23>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:77:3-77:27
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:77:3-77:11
              kind = Local
              name = <U lr_first>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:77:14-77:27
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:77:15-77:20
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/range.rb:77:15-77:20
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <build-range>>
                block = nullptr
                pos_args = 3
                args = [
                  Literal{ loc = test/testdata/desugar/range.rb:77:15-77:16, value = 1 }
                  Literal{ loc = test/testdata/desugar/range.rb:77:18-77:20, value = 42 }
                  Literal{ loc = test/testdata/desugar/range.rb:77:15-77:20, value = false }
                ]
              }
              fun = <U first>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:78:3-78:26
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:78:3-78:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:78:17-78:25
                kind = Local
                name = <U lr_first>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:80:3-80:28
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:80:3-80:10
              kind = Local
              name = <U lr_last>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:80:13-80:28
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:80:14-80:22
                flags = {}
                recv = ConstantLit{
                  loc = test/testdata/desugar/range.rb:80:14-80:22
                  symbol = (class ::<Magic>)
                  orig = nullptr
                }
                fun = <U <build-range>>
                block = nullptr
                pos_args = 3
                args = [
                  Literal{ loc = test/testdata/desugar/range.rb:80:14-80:17, value = "a" }
                  Literal{ loc = test/testdata/desugar/range.rb:80:19-80:22, value = "z" }
                  Literal{ loc = test/testdata/desugar/range.rb:80:14-80:22, value = false }
                ]
              }
              fun = <U last>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:81:3-81:25
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:81:3-81:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:81:17-81:24
                kind = Local
                name = <U lr_last>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:85:3-85:18
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:85:3-85:6
              kind = Local
              name = <U rn1>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:85:9-85:18
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:85:9-85:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:86:3-86:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:86:3-86:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:86:17-86:20
                kind = Local
                name = <U rn1>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:88:3-88:23
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:88:3-88:6
              kind = Local
              name = <U rn2>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:88:9-88:23
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:88:9-88:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 1
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:88:19-88:22, value = nil }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:89:3-89:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:89:3-89:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:89:17-89:20
                kind = Local
                name = <U rn2>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:91:3-91:24
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:91:3-91:6
              kind = Local
              name = <U rn3>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:91:9-91:24
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:91:9-91:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:91:19-91:20, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:91:22-91:23, value = 2 }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:92:3-92:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:92:3-92:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:92:17-92:20
                kind = Local
                name = <U rn3>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:94:3-94:30
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:94:3-94:6
              kind = Local
              name = <U rn4>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:94:9-94:30
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:94:9-94:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:94:19-94:20, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:94:22-94:23, value = 2 }
                Literal{ loc = test/testdata/desugar/range.rb:94:25-94:29, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:95:3-95:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:95:3-95:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:95:17-95:20
                kind = Local
                name = <U rn4>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:97:3-97:26
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:97:3-97:6
              kind = Local
              name = <U rn5>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:97:9-97:26
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:97:9-97:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:97:19-97:20, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:97:22-97:25, value = nil }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:98:3-98:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:98:3-98:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:98:17-98:20
                kind = Local
                name = <U rn5>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:100:3-100:27
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:100:3-100:6
              kind = Local
              name = <U rn6>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:100:9-100:27
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:100:9-100:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:100:19-100:20, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:100:22-100:26, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:101:3-101:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:101:3-101:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:101:17-101:20
                kind = Local
                name = <U rn6>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:103:3-103:27
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:103:3-103:6
              kind = Local
              name = <U rn7>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:103:9-103:27
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:103:9-103:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:103:19-103:22, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:103:24-103:26, value = 42 }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:104:3-104:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:104:3-104:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:104:17-104:20
                kind = Local
                name = <U rn7>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:106:3-106:28
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:106:3-106:6
              kind = Local
              name = <U rn8>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:106:9-106:28
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:106:9-106:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:106:19-106:22, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:106:24-106:27, value = nil }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:107:3-107:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:107:3-107:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:107:17-107:20
                kind = Local
                name = <U rn8>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:109:3-109:26
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:109:3-109:6
              kind = Local
              name = <U rn9>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:109:9-109:26
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:109:9-109:14
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:109:19-109:20, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:109:22-109:25, value = "c" }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:110:3-110:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:110:3-110:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:110:17-110:20
                kind = Local
                name = <U rn9>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:112:3-112:32
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:112:3-112:7
              kind = Local
              name = <U rn10>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:112:10-112:32
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:112:10-112:15
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:112:20-112:27
                  kind = Local
                  name = <U untyped>
                }
                Literal{ loc = test/testdata/desugar/range.rb:112:29-112:31, value = 42 }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:113:3-113:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:113:3-113:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:113:17-113:21
                kind = Local
                name = <U rn10>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:115:3-115:31
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:115:3-115:7
              kind = Local
              name = <U rn11>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:115:10-115:31
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:115:10-115:15
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:115:20-115:21, value = 1 }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:115:23-115:30
                  kind = Local
                  name = <U untyped>
                }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:116:3-116:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:116:3-116:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:116:17-116:21
                kind = Local
                name = <U rn11>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:118:3-118:37
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:118:3-118:7
              kind = Local
              name = <U rn12>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:118:10-118:37
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:118:10-118:15
                cnst = <C <U Range>>
                scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:118:20-118:27
                  kind = Local
                  name = <U untyped>
                }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:118:29-118:36
                  kind = Local
                  name = <U untyped>
                }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:119:3-119:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:119:3-119:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:119:17-119:21
                kind = Local
                name = <U rn12>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:121:3-121:36
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:121:3-121:11
              kind = Local
              name = <U rn_first>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:121:14-121:36
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:121:14-121:30
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:121:14-121:19
                  cnst = <C <U Range>>
                  scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                }
                fun = <U new>
                block = nullptr
                pos_args = 2
                args = [
                  Literal{ loc = test/testdata/desugar/range.rb:121:24-121:25, value = 1 }
                  Literal{ loc = test/testdata/desugar/range.rb:121:27-121:29, value = 42 }
                ]
              }
              fun = <U first>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:122:3-122:26
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:122:3-122:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:122:17-122:25
                kind = Local
                name = <U rn_first>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:124:3-124:37
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:124:3-124:10
              kind = Local
              name = <U rn_last>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:124:13-124:37
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:124:13-124:32
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:124:13-124:18
                  cnst = <C <U Range>>
                  scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                }
                fun = <U new>
                block = nullptr
                pos_args = 2
                args = [
                  Literal{ loc = test/testdata/desugar/range.rb:124:23-124:26, value = "a" }
                  Literal{ loc = test/testdata/desugar/range.rb:124:28-124:31, value = "z" }
                ]
              }
              fun = <U last>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:125:3-125:25
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:125:3-125:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:125:17-125:24
                kind = Local
                name = <U rn_last>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:129:3-129:21
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:129:3-129:6
              kind = Local
              name = <U tr1>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:129:9-129:21
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/range.rb:129:9-129:17
                cnst = <C <U Range>>
                scope = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:129:9-129:10
                  cnst = <C <U T>>
                  scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                }
              }
              fun = <U new>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:130:3-130:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:130:3-130:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:130:17-130:20
                kind = Local
                name = <U tr1>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:132:3-132:30
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:132:3-132:6
              kind = Local
              name = <U tr2>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:132:9-132:30
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:132:9-132:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:132:9-132:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:132:9-132:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:132:18-132:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:133:3-133:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:133:3-133:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:133:17-133:20
                kind = Local
                name = <U tr2>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:135:3-135:36
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:135:3-135:6
              kind = Local
              name = <U tr3>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:135:9-135:36
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:135:9-135:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:135:9-135:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:135:9-135:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:135:18-135:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:135:31-135:32, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:135:34-135:35, value = 2 }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:136:3-136:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:136:3-136:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:136:17-136:20
                kind = Local
                name = <U tr3>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:138:3-138:42
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:138:3-138:6
              kind = Local
              name = <U tr4>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:138:9-138:42
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:138:9-138:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:138:9-138:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:138:9-138:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:138:18-138:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 3
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:138:31-138:32, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:138:34-138:35, value = 2 }
                Literal{ loc = test/testdata/desugar/range.rb:138:37-138:41, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:139:3-139:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:139:3-139:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:139:17-139:20
                kind = Local
                name = <U tr4>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:141:3-141:38
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:141:3-141:6
              kind = Local
              name = <U tr5>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:141:9-141:38
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:141:9-141:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:141:9-141:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:141:9-141:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:141:18-141:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:141:31-141:32, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:141:34-141:37, value = nil }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:142:3-142:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:142:3-142:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:142:17-142:20
                kind = Local
                name = <U tr5>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:144:3-144:39
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:144:3-144:6
              kind = Local
              name = <U tr6>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:144:9-144:39
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:144:9-144:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:144:9-144:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:144:9-144:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:144:18-144:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:144:31-144:32, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:144:34-144:38, value = true }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:145:3-145:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:145:3-145:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:145:17-145:20
                kind = Local
                name = <U tr6>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:147:3-147:39
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:147:3-147:6
              kind = Local
              name = <U tr7>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:147:9-147:39
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:147:9-147:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:147:9-147:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:147:9-147:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:147:18-147:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:147:31-147:34, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:147:36-147:38, value = 42 }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:148:3-148:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:148:3-148:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:148:17-148:20
                kind = Local
                name = <U tr7>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:150:3-150:40
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:150:3-150:6
              kind = Local
              name = <U tr8>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:150:9-150:40
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:150:9-150:26
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:150:9-150:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:150:9-150:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:150:18-150:25
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:150:31-150:34, value = nil }
                Literal{ loc = test/testdata/desugar/range.rb:150:36-150:39, value = nil }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:151:3-151:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:151:3-151:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:151:17-151:20
                kind = Local
                name = <U tr8>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:153:3-153:40
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:153:3-153:6
              kind = Local
              name = <U tr9>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:153:9-153:40
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:153:9-153:28
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:153:9-153:17
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:153:9-153:10
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  Send{
                    loc = test/testdata/desugar/range.rb:153:18-153:27
                    flags = {}
                    recv = UnresolvedConstantLit{
                      loc = test/testdata/desugar/range.rb:153:18-153:19
                      cnst = <C <U T>>
                      scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                    }
                    fun = <U untyped>
                    block = nullptr
                    pos_args = 0
                    args = [
                    ]
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:153:33-153:34, value = 1 }
                Literal{ loc = test/testdata/desugar/range.rb:153:36-153:39, value = "c" }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:154:3-154:21
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:154:3-154:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:154:17-154:20
                kind = Local
                name = <U tr9>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:156:3-156:44
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:156:3-156:7
              kind = Local
              name = <U tr10>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:156:10-156:44
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:156:10-156:27
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:156:10-156:18
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:156:10-156:11
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:156:19-156:26
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:156:32-156:39
                  kind = Local
                  name = <U untyped>
                }
                Literal{ loc = test/testdata/desugar/range.rb:156:41-156:43, value = 42 }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:157:3-157:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:157:3-157:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:157:17-157:21
                kind = Local
                name = <U tr10>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:159:3-159:43
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:159:3-159:7
              kind = Local
              name = <U tr11>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:159:10-159:43
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:159:10-159:27
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:159:10-159:18
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:159:10-159:11
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:159:19-159:26
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/range.rb:159:32-159:33, value = 1 }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:159:35-159:42
                  kind = Local
                  name = <U untyped>
                }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:160:3-160:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:160:3-160:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:160:17-160:21
                kind = Local
                name = <U tr11>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:162:3-162:49
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:162:3-162:7
              kind = Local
              name = <U tr12>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:162:10-162:49
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:162:10-162:27
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/range.rb:162:10-162:18
                  cnst = <C <U Range>>
                  scope = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:162:10-162:11
                    cnst = <C <U T>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                }
                fun = <U []>
                block = nullptr
                pos_args = 1
                args = [
                  UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:162:19-162:26
                    cnst = <C <U Integer>>
                    scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                  }
                ]
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:162:32-162:39
                  kind = Local
                  name = <U untyped>
                }
                UnresolvedIdent{
                  loc = test/testdata/desugar/range.rb:162:41-162:48
                  kind = Local
                  name = <U untyped>
                }
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:163:3-163:22
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:163:3-163:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:163:17-163:21
                kind = Local
                name = <U tr12>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:165:3-165:48
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:165:3-165:11
              kind = Local
              name = <U tr_first>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:165:14-165:48
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:165:14-165:42
                flags = {}
                recv = Send{
                  loc = test/testdata/desugar/range.rb:165:14-165:31
                  flags = {}
                  recv = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:165:14-165:22
                    cnst = <C <U Range>>
                    scope = UnresolvedConstantLit{
                      loc = test/testdata/desugar/range.rb:165:14-165:15
                      cnst = <C <U T>>
                      scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                    }
                  }
                  fun = <U []>
                  block = nullptr
                  pos_args = 1
                  args = [
                    UnresolvedConstantLit{
                      loc = test/testdata/desugar/range.rb:165:23-165:30
                      cnst = <C <U Integer>>
                      scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                    }
                  ]
                }
                fun = <U new>
                block = nullptr
                pos_args = 2
                args = [
                  Literal{ loc = test/testdata/desugar/range.rb:165:36-165:37, value = 1 }
                  Literal{ loc = test/testdata/desugar/range.rb:165:39-165:41, value = 42 }
                ]
              }
              fun = <U first>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
          Send{
            loc = test/testdata/desugar/range.rb:166:3-166:26
            flags = {}
            recv = UnresolvedConstantLit{
              loc = test/testdata/desugar/range.rb:166:3-166:4
              cnst = <C <U T>>
              scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
            }
            fun = <U reveal_type>
            block = nullptr
            pos_args = 1
            args = [
              UnresolvedIdent{
                loc = test/testdata/desugar/range.rb:166:17-166:25
                kind = Local
                name = <U tr_first>
              }
            ]
          }
          Assign{
            loc = test/testdata/desugar/range.rb:168:3-168:48
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:168:3-168:10
              kind = Local
              name = <U tr_last>
            }
            rhs = Send{
              loc = test/testdata/desugar/range.rb:168:13-168:48
              flags = {}
              recv = Send{
                loc = test/testdata/desugar/range.rb:168:13-168:43
                flags = {}
                recv = Send{
                  loc = test/testdata/desugar/range.rb:168:13-168:29
                  flags = {}
                  recv = UnresolvedConstantLit{
                    loc = test/testdata/desugar/range.rb:168:13-168:21
                    cnst = <C <U Range>>
                    scope = UnresolvedConstantLit{
                      loc = test/testdata/desugar/range.rb:168:13-168:14
                      cnst = <C <U T>>
                      scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                    }
                  }
                  fun = <U []>
                  block = nullptr
                  pos_args = 1
                  args = [
                    UnresolvedConstantLit{
                      loc = test/testdata/desugar/range.rb:168:22-168:28
                      cnst = <C <U String>>
                      scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
                    }
                  ]
                }
                fun = <U new>
                block = nullptr
                pos_args = 2
                args = [
                  Literal{ loc = test/testdata/desugar/range.rb:168:34-168:37, value = "a" }
                  Literal{ loc = test/testdata/desugar/range.rb:168:39-168:42, value = "z" }
                ]
              }
              fun = <U last>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          }
        ],
        expr = Send{
          loc = test/testdata/desugar/range.rb:169:3-169:25
          flags = {}
          recv = UnresolvedConstantLit{
            loc = test/testdata/desugar/range.rb:169:3-169:4
            cnst = <C <U T>>
            scope = EmptyTree{ loc = test/testdata/desugar/range.rb }
          }
          fun = <U reveal_type>
          block = nullptr
          pos_args = 1
          args = [
            UnresolvedIdent{
              loc = test/testdata/desugar/range.rb:169:17-169:24
              kind = Local
              name = <U tr_last>
            }
          ]
        }
      }
    }
  ]
}
