ClassDef{
  loc = test/testdata/desugar/regexp_strict.rb:3:1-13:4
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/regexp_strict.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/regexp_strict.rb:3:1-13:4
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    Send{
      loc = test/testdata/desugar/regexp_strict.rb:3:1-3:14
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/regexp_strict.rb:3:1-3:1
        localVariable = <U <self>>
      }
      fun = <U extend>
      block = nullptr
      pos_args = 1
      args = [
        UnresolvedConstantLit{
          loc = test/testdata/desugar/regexp_strict.rb:3:8-3:14
          cnst = <C <U Sig>>
          scope = UnresolvedConstantLit{
            loc = test/testdata/desugar/regexp_strict.rb:3:8-3:9
            cnst = <C <U T>>
            scope = EmptyTree{ loc = test/testdata/desugar/regexp_strict.rb }
          }
        }
      ]
    }

    ClassDef{
      loc = test/testdata/desugar/regexp_strict.rb:5:1-7:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/regexp_strict.rb:5:7-5:8
        cnst = <C <U A>>
        scope = EmptyTree{ loc = test/testdata/desugar/regexp_strict.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [ConstantLit{
          loc = test/testdata/desugar/regexp_strict.rb:5:1-7:4
          symbol = (class ::<todo sym>)
          orig = nullptr
        }]
      rhs = [
        Assign{
          loc = test/testdata/desugar/regexp_strict.rb:6:3-6:12
          lhs = UnresolvedConstantLit{
            loc = test/testdata/desugar/regexp_strict.rb:6:3-6:4
            cnst = <C <U X>>
            scope = EmptyTree{ loc = test/testdata/desugar/regexp_strict.rb }
          }
          rhs = Send{
            loc = test/testdata/desugar/regexp_strict.rb:6:7-6:12
            flags = {}
            recv = ConstantLit{
              loc = test/testdata/desugar/regexp_strict.rb:6:7-6:12
              symbol = (class ::Regexp)
              orig = nullptr
            }
            fun = <U new>
            block = nullptr
            pos_args = 2
            args = [
              Literal{ loc = test/testdata/desugar/regexp_strict.rb:6:7-6:12, value = "foo" }
              Literal{ loc = test/testdata/desugar/regexp_strict.rb:6:11-6:12, value = 0 }
            ]
          }
        }
      ]
    }

    Send{
      loc = test/testdata/desugar/regexp_strict.rb:9:1-9:11
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/regexp_strict.rb:9:1-9:1
        localVariable = <U <self>>
      }
      fun = <U sig>
      block = Block {
        loc = test/testdata/desugar/regexp_strict.rb:9:1-9:11
        args = [
        ]
        body = Send{
          loc = test/testdata/desugar/regexp_strict.rb:9:6-9:10
          flags = {privateOk}
          recv = Local{
            loc = test/testdata/desugar/regexp_strict.rb:9:6-9:6
            localVariable = <U <self>>
          }
          fun = <U void>
          block = nullptr
          pos_args = 0
          args = [
          ]
        }
      }
      pos_args = 0
      args = [
      ]
    }

    MethodDef{
      loc = test/testdata/desugar/regexp_strict.rb:10:1-13:4
      flags = {}
      name = <U foo><<U <todo method>>>
      args = [BlockArg{ loc = test/testdata/desugar/regexp_strict.rb, expr = UnresolvedIdent{
          loc = test/testdata/desugar/regexp_strict.rb
          kind = Local
          name = <U <blk>>
        } }]
      rhs = InsSeq{
        loc = test/testdata/desugar/regexp_strict.rb:11:3-12:8
        stats = [
          Assign{
            loc = test/testdata/desugar/regexp_strict.rb:11:3-11:12
            lhs = UnresolvedIdent{
              loc = test/testdata/desugar/regexp_strict.rb:11:3-11:4
              kind = Local
              name = <U a>
            }
            rhs = Send{
              loc = test/testdata/desugar/regexp_strict.rb:11:7-11:12
              flags = {}
              recv = ConstantLit{
                loc = test/testdata/desugar/regexp_strict.rb:11:7-11:12
                symbol = (class ::Regexp)
                orig = nullptr
              }
              fun = <U new>
              block = nullptr
              pos_args = 2
              args = [
                Literal{ loc = test/testdata/desugar/regexp_strict.rb:11:7-11:12, value = "foo" }
                Literal{ loc = test/testdata/desugar/regexp_strict.rb:11:11-11:12, value = 0 }
              ]
            }
          }
        ],
        expr = Assign{
          loc = test/testdata/desugar/regexp_strict.rb:12:3-12:8
          lhs = UnresolvedIdent{
            loc = test/testdata/desugar/regexp_strict.rb:12:3-12:4
            kind = Local
            name = <U a>
          }
          rhs = Literal{ loc = test/testdata/desugar/regexp_strict.rb:12:7-12:8, value = 1 }
        }
      }
    }
  ]
}
