ClassDef{
  loc = test/testdata/desugar/sclass_inheritance.rb:2:1-35:5
  kind = class
  name = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
  symbol = <C <U <root>>>
  ancestors = [ConstantLit{
      loc = test/testdata/desugar/sclass_inheritance.rb:2:1-35:5
      symbol = (class ::<todo sym>)
      orig = nullptr
    }]
  rhs = [
    ClassDef{
      loc = test/testdata/desugar/sclass_inheritance.rb:2:1-2:15
      kind = module
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/sclass_inheritance.rb:2:8-2:10
        cnst = <C <U MM>>
        scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = []
      rhs = [
        EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
      ]
    }

    ClassDef{
      loc = test/testdata/desugar/sclass_inheritance.rb:4:1-12:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/sclass_inheritance.rb:4:7-4:8
        cnst = <C <U A>>
        scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [ConstantLit{
          loc = test/testdata/desugar/sclass_inheritance.rb:4:1-12:4
          symbol = (class ::<todo sym>)
          orig = nullptr
        }]
      rhs = [
        ClassDef{
          loc = test/testdata/desugar/sclass_inheritance.rb:5:5-11:8
          kind = class
          name = UnresolvedIdent{
            loc = test/testdata/desugar/sclass_inheritance.rb:5:14-5:18
            kind = Class
            name = <U <singleton class>>
          }
          symbol = <C <U <todo sym>>>
          ancestors = []
          rhs = [
            Send{
              loc = test/testdata/desugar/sclass_inheritance.rb:6:9-6:19
              flags = {privateOk}
              recv = Local{
                loc = test/testdata/desugar/sclass_inheritance.rb:6:9-6:9
                localVariable = <U <self>>
              }
              fun = <U include>
              block = nullptr
              pos_args = 1
              args = [
                UnresolvedConstantLit{
                  loc = test/testdata/desugar/sclass_inheritance.rb:6:17-6:19
                  cnst = <C <U MM>>
                  scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
                }
              ]
            }

            MethodDef{
              loc = test/testdata/desugar/sclass_inheritance.rb:8:9-10:12
              flags = {}
              name = <U newer><<U <todo method>>>
              args = [BlockArg{ loc = test/testdata/desugar/sclass_inheritance.rb, expr = UnresolvedIdent{
                  loc = test/testdata/desugar/sclass_inheritance.rb
                  kind = Local
                  name = <U <blk>>
                } }]
              rhs = Send{
                loc = test/testdata/desugar/sclass_inheritance.rb:9:13-9:16
                flags = {privateOk}
                recv = Local{
                  loc = test/testdata/desugar/sclass_inheritance.rb:9:13-9:13
                  localVariable = <U <self>>
                }
                fun = <U new>
                block = nullptr
                pos_args = 0
                args = [
                ]
              }
            }
          ]
        }
      ]
    }

    ClassDef{
      loc = test/testdata/desugar/sclass_inheritance.rb:14:1-20:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/sclass_inheritance.rb:14:7-14:8
        cnst = <C <U B>>
        scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [ConstantLit{
          loc = test/testdata/desugar/sclass_inheritance.rb:14:1-20:4
          symbol = (class ::<todo sym>)
          orig = nullptr
        }]
      rhs = [
        Send{
          loc = test/testdata/desugar/sclass_inheritance.rb:15:5-15:14
          flags = {privateOk}
          recv = Local{
            loc = test/testdata/desugar/sclass_inheritance.rb:15:5-15:5
            localVariable = <U <self>>
          }
          fun = <U extend>
          block = nullptr
          pos_args = 1
          args = [
            UnresolvedConstantLit{
              loc = test/testdata/desugar/sclass_inheritance.rb:15:12-15:14
              cnst = <C <U MM>>
              scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
            }
          ]
        }

        MethodDef{
          loc = test/testdata/desugar/sclass_inheritance.rb:17:5-19:8
          flags = {self}
          name = <U newer><<U <todo method>>>
          args = [BlockArg{ loc = test/testdata/desugar/sclass_inheritance.rb, expr = UnresolvedIdent{
              loc = test/testdata/desugar/sclass_inheritance.rb
              kind = Local
              name = <U <blk>>
            } }]
          rhs = Send{
            loc = test/testdata/desugar/sclass_inheritance.rb:18:9-18:12
            flags = {privateOk}
            recv = Local{
              loc = test/testdata/desugar/sclass_inheritance.rb:18:9-18:9
              localVariable = <U <self>>
            }
            fun = <U new>
            block = nullptr
            pos_args = 0
            args = [
            ]
          }
        }
      ]
    }

    ClassDef{
      loc = test/testdata/desugar/sclass_inheritance.rb:22:1-28:4
      kind = class
      name = UnresolvedConstantLit{
        loc = test/testdata/desugar/sclass_inheritance.rb:22:7-22:8
        cnst = <C <U C>>
        scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
      }
      symbol = <C <U <todo sym>>>
      ancestors = [UnresolvedConstantLit{
          loc = test/testdata/desugar/sclass_inheritance.rb:22:11-22:12
          cnst = <C <U A>>
          scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
        }]
      rhs = [
        ClassDef{
          loc = test/testdata/desugar/sclass_inheritance.rb:23:4-27:7
          kind = class
          name = UnresolvedIdent{
            loc = test/testdata/desugar/sclass_inheritance.rb:23:13-23:17
            kind = Class
            name = <U <singleton class>>
          }
          symbol = <C <U <todo sym>>>
          ancestors = []
          rhs = [
            MethodDef{
              loc = test/testdata/desugar/sclass_inheritance.rb:24:7-26:10
              flags = {}
              name = <U newerer><<U <todo method>>>
              args = [BlockArg{ loc = test/testdata/desugar/sclass_inheritance.rb, expr = UnresolvedIdent{
                  loc = test/testdata/desugar/sclass_inheritance.rb
                  kind = Local
                  name = <U <blk>>
                } }]
              rhs = Send{
                loc = test/testdata/desugar/sclass_inheritance.rb:25:10-25:15
                flags = {privateOk}
                recv = Local{
                  loc = test/testdata/desugar/sclass_inheritance.rb:25:10-25:10
                  localVariable = <U <self>>
                }
                fun = <U newer>
                block = nullptr
                pos_args = 0
                args = [
                ]
              }
            }
          ]
        }
      ]
    }

    MethodDef{
      loc = test/testdata/desugar/sclass_inheritance.rb:30:1-34:4
      flags = {}
      name = <U main><<U <todo method>>>
      args = [BlockArg{ loc = test/testdata/desugar/sclass_inheritance.rb, expr = UnresolvedIdent{
          loc = test/testdata/desugar/sclass_inheritance.rb
          kind = Local
          name = <U <blk>>
        } }]
      rhs = InsSeq{
        loc = test/testdata/desugar/sclass_inheritance.rb:31:5-33:19
        stats = [
          Send{
            loc = test/testdata/desugar/sclass_inheritance.rb:31:5-31:17
            flags = {privateOk}
            recv = Local{
              loc = test/testdata/desugar/sclass_inheritance.rb:31:5-31:5
              localVariable = <U <self>>
            }
            fun = <U puts>
            block = nullptr
            pos_args = 1
            args = [
              Send{
                loc = test/testdata/desugar/sclass_inheritance.rb:31:10-31:17
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/sclass_inheritance.rb:31:10-31:11
                  cnst = <C <U A>>
                  scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
                }
                fun = <U newer>
                block = nullptr
                pos_args = 0
                args = [
                ]
              }
            ]
          }
          Send{
            loc = test/testdata/desugar/sclass_inheritance.rb:32:5-32:17
            flags = {privateOk}
            recv = Local{
              loc = test/testdata/desugar/sclass_inheritance.rb:32:5-32:5
              localVariable = <U <self>>
            }
            fun = <U puts>
            block = nullptr
            pos_args = 1
            args = [
              Send{
                loc = test/testdata/desugar/sclass_inheritance.rb:32:10-32:17
                flags = {}
                recv = UnresolvedConstantLit{
                  loc = test/testdata/desugar/sclass_inheritance.rb:32:10-32:11
                  cnst = <C <U B>>
                  scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
                }
                fun = <U newer>
                block = nullptr
                pos_args = 0
                args = [
                ]
              }
            ]
          }
        ],
        expr = Send{
          loc = test/testdata/desugar/sclass_inheritance.rb:33:5-33:19
          flags = {privateOk}
          recv = Local{
            loc = test/testdata/desugar/sclass_inheritance.rb:33:5-33:5
            localVariable = <U <self>>
          }
          fun = <U puts>
          block = nullptr
          pos_args = 1
          args = [
            Send{
              loc = test/testdata/desugar/sclass_inheritance.rb:33:10-33:19
              flags = {}
              recv = UnresolvedConstantLit{
                loc = test/testdata/desugar/sclass_inheritance.rb:33:10-33:11
                cnst = <C <U C>>
                scope = EmptyTree{ loc = test/testdata/desugar/sclass_inheritance.rb }
              }
              fun = <U newerer>
              block = nullptr
              pos_args = 0
              args = [
              ]
            }
          ]
        }
      }
    }

    Send{
      loc = test/testdata/desugar/sclass_inheritance.rb:35:1-35:5
      flags = {privateOk}
      recv = Local{
        loc = test/testdata/desugar/sclass_inheritance.rb:35:1-35:1
        localVariable = <U <self>>
      }
      fun = <U main>
      block = nullptr
      pos_args = 0
      args = [
      ]
    }
  ]
}
